LogConfig: true
Logger:
  AppName: openclick
  Build: dev
  Level: debug
ConfigReader:
  Name: ""
  Format: ""
  Consul:
    Address: ""
    Token: ""
    Path: ""
  Zookeeper:
    Address: ""
    Path: ""
    Username: ""
    Password: ""
AppNames:
- HTTP_SERVER
- GRPC_SERVER
Server:
  GRPCPort: 9094
  HTTPPort: 9093
  CORS:
    Enabled: false
Repository:
  Name : PostgreSQL
  PostgreSQL:
    Name: Postgres
    Postgres:
      primary:
        Host: 192.168.1.100
        Port: 5432
        Username: "admin"
        Password: OSwfiTlc1r5W7Z
        DBName: openclick
        SSLMode: disable
        MaxOpenConns: 10
        MaxIdleConns: 5
        ConnMaxLifetime: 5m
        ConnMaxIdleTime: 5m
      replica: []
  ClickHouse:
    Host: "192.168.1.100"
    Port: 9096
    Username: "admin"
    Password: OSwfiTlc1r5W7Z
    Database: openclick
    MaxOpenConns: 10
    MaxIdleConns: 5
Service: {}
Debug:
  Enabled: true
  EnablePprof: true