// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/openclick/v1/dashboard.proto

package openclick_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DashboardResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DashboardResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DashboardResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DashboardResponseMultiError, or nil if none found.
func (m *DashboardResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DashboardResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for ItemCount

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DashboardResponseValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DashboardResponseValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DashboardResponseValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DashboardResponseMultiError(errors)
	}

	return nil
}

// DashboardResponseMultiError is an error wrapping multiple validation errors
// returned by DashboardResponse.ValidateAll() if the designated constraints
// aren't met.
type DashboardResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DashboardResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DashboardResponseMultiError) AllErrors() []error { return m }

// DashboardResponseValidationError is the validation error returned by
// DashboardResponse.Validate if the designated constraints aren't met.
type DashboardResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DashboardResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DashboardResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DashboardResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DashboardResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DashboardResponseValidationError) ErrorName() string {
	return "DashboardResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DashboardResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDashboardResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DashboardResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DashboardResponseValidationError{}

// Validate checks the field values on DashboardItemResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DashboardItemResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DashboardItemResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DashboardItemResponseMultiError, or nil if none found.
func (m *DashboardItemResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DashboardItemResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for DashboardId

	// no validation rules for Name

	// no validation rules for Type

	if all {
		switch v := interface{}(m.GetQuery()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DashboardItemResponseValidationError{
					field:  "Query",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DashboardItemResponseValidationError{
					field:  "Query",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetQuery()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DashboardItemResponseValidationError{
				field:  "Query",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetPosition()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DashboardItemResponseValidationError{
					field:  "Position",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DashboardItemResponseValidationError{
					field:  "Position",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPosition()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DashboardItemResponseValidationError{
				field:  "Position",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DashboardItemResponseMultiError(errors)
	}

	return nil
}

// DashboardItemResponseMultiError is an error wrapping multiple validation
// errors returned by DashboardItemResponse.ValidateAll() if the designated
// constraints aren't met.
type DashboardItemResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DashboardItemResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DashboardItemResponseMultiError) AllErrors() []error { return m }

// DashboardItemResponseValidationError is the validation error returned by
// DashboardItemResponse.Validate if the designated constraints aren't met.
type DashboardItemResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DashboardItemResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DashboardItemResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DashboardItemResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DashboardItemResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DashboardItemResponseValidationError) ErrorName() string {
	return "DashboardItemResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DashboardItemResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDashboardItemResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DashboardItemResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DashboardItemResponseValidationError{}

// Validate checks the field values on ListDashboardsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListDashboardsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListDashboardsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListDashboardsRequestMultiError, or nil if none found.
func (m *ListDashboardsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListDashboardsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectId

	if len(errors) > 0 {
		return ListDashboardsRequestMultiError(errors)
	}

	return nil
}

// ListDashboardsRequestMultiError is an error wrapping multiple validation
// errors returned by ListDashboardsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListDashboardsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListDashboardsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListDashboardsRequestMultiError) AllErrors() []error { return m }

// ListDashboardsRequestValidationError is the validation error returned by
// ListDashboardsRequest.Validate if the designated constraints aren't met.
type ListDashboardsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListDashboardsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListDashboardsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListDashboardsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListDashboardsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListDashboardsRequestValidationError) ErrorName() string {
	return "ListDashboardsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListDashboardsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListDashboardsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListDashboardsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListDashboardsRequestValidationError{}

// Validate checks the field values on ListDashboardsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListDashboardsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListDashboardsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListDashboardsResponseMultiError, or nil if none found.
func (m *ListDashboardsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListDashboardsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetResults() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListDashboardsResponseValidationError{
						field:  fmt.Sprintf("Results[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListDashboardsResponseValidationError{
						field:  fmt.Sprintf("Results[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListDashboardsResponseValidationError{
					field:  fmt.Sprintf("Results[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListDashboardsResponseMultiError(errors)
	}

	return nil
}

// ListDashboardsResponseMultiError is an error wrapping multiple validation
// errors returned by ListDashboardsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListDashboardsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListDashboardsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListDashboardsResponseMultiError) AllErrors() []error { return m }

// ListDashboardsResponseValidationError is the validation error returned by
// ListDashboardsResponse.Validate if the designated constraints aren't met.
type ListDashboardsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListDashboardsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListDashboardsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListDashboardsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListDashboardsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListDashboardsResponseValidationError) ErrorName() string {
	return "ListDashboardsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListDashboardsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListDashboardsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListDashboardsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListDashboardsResponseValidationError{}

// Validate checks the field values on CreateDashboardRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateDashboardRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateDashboardRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateDashboardRequestMultiError, or nil if none found.
func (m *CreateDashboardRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateDashboardRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectId

	// no validation rules for Name

	if len(errors) > 0 {
		return CreateDashboardRequestMultiError(errors)
	}

	return nil
}

// CreateDashboardRequestMultiError is an error wrapping multiple validation
// errors returned by CreateDashboardRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateDashboardRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateDashboardRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateDashboardRequestMultiError) AllErrors() []error { return m }

// CreateDashboardRequestValidationError is the validation error returned by
// CreateDashboardRequest.Validate if the designated constraints aren't met.
type CreateDashboardRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateDashboardRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateDashboardRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateDashboardRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateDashboardRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateDashboardRequestValidationError) ErrorName() string {
	return "CreateDashboardRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateDashboardRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateDashboardRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateDashboardRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateDashboardRequestValidationError{}

// Validate checks the field values on GetDashboardRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetDashboardRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDashboardRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDashboardRequestMultiError, or nil if none found.
func (m *GetDashboardRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDashboardRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectId

	// no validation rules for DashboardId

	if len(errors) > 0 {
		return GetDashboardRequestMultiError(errors)
	}

	return nil
}

// GetDashboardRequestMultiError is an error wrapping multiple validation
// errors returned by GetDashboardRequest.ValidateAll() if the designated
// constraints aren't met.
type GetDashboardRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDashboardRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDashboardRequestMultiError) AllErrors() []error { return m }

// GetDashboardRequestValidationError is the validation error returned by
// GetDashboardRequest.Validate if the designated constraints aren't met.
type GetDashboardRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDashboardRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDashboardRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDashboardRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDashboardRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDashboardRequestValidationError) ErrorName() string {
	return "GetDashboardRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetDashboardRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDashboardRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDashboardRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDashboardRequestValidationError{}

// Validate checks the field values on GetDashboardResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetDashboardResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDashboardResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDashboardResponseMultiError, or nil if none found.
func (m *GetDashboardResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDashboardResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetDashboardResponseValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetDashboardResponseValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetDashboardResponseValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetDashboardResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetDashboardResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetDashboardResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetDashboardResponseMultiError(errors)
	}

	return nil
}

// GetDashboardResponseMultiError is an error wrapping multiple validation
// errors returned by GetDashboardResponse.ValidateAll() if the designated
// constraints aren't met.
type GetDashboardResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDashboardResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDashboardResponseMultiError) AllErrors() []error { return m }

// GetDashboardResponseValidationError is the validation error returned by
// GetDashboardResponse.Validate if the designated constraints aren't met.
type GetDashboardResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDashboardResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDashboardResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDashboardResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDashboardResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDashboardResponseValidationError) ErrorName() string {
	return "GetDashboardResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetDashboardResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDashboardResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDashboardResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDashboardResponseValidationError{}

// Validate checks the field values on DeleteDashboardRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteDashboardRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteDashboardRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteDashboardRequestMultiError, or nil if none found.
func (m *DeleteDashboardRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteDashboardRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectId

	// no validation rules for DashboardId

	if len(errors) > 0 {
		return DeleteDashboardRequestMultiError(errors)
	}

	return nil
}

// DeleteDashboardRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteDashboardRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteDashboardRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteDashboardRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteDashboardRequestMultiError) AllErrors() []error { return m }

// DeleteDashboardRequestValidationError is the validation error returned by
// DeleteDashboardRequest.Validate if the designated constraints aren't met.
type DeleteDashboardRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteDashboardRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteDashboardRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteDashboardRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteDashboardRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteDashboardRequestValidationError) ErrorName() string {
	return "DeleteDashboardRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteDashboardRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteDashboardRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteDashboardRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteDashboardRequestValidationError{}

// Validate checks the field values on DeleteDashboardResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteDashboardResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteDashboardResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteDashboardResponseMultiError, or nil if none found.
func (m *DeleteDashboardResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteDashboardResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteDashboardResponseMultiError(errors)
	}

	return nil
}

// DeleteDashboardResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteDashboardResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteDashboardResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteDashboardResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteDashboardResponseMultiError) AllErrors() []error { return m }

// DeleteDashboardResponseValidationError is the validation error returned by
// DeleteDashboardResponse.Validate if the designated constraints aren't met.
type DeleteDashboardResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteDashboardResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteDashboardResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteDashboardResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteDashboardResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteDashboardResponseValidationError) ErrorName() string {
	return "DeleteDashboardResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteDashboardResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteDashboardResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteDashboardResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteDashboardResponseValidationError{}

// Validate checks the field values on CreateDashboardItemRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateDashboardItemRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateDashboardItemRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateDashboardItemRequestMultiError, or nil if none found.
func (m *CreateDashboardItemRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateDashboardItemRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectId

	// no validation rules for DashboardId

	// no validation rules for Name

	// no validation rules for Type

	if all {
		switch v := interface{}(m.GetQuery()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateDashboardItemRequestValidationError{
					field:  "Query",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateDashboardItemRequestValidationError{
					field:  "Query",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetQuery()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateDashboardItemRequestValidationError{
				field:  "Query",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetPosition()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateDashboardItemRequestValidationError{
					field:  "Position",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateDashboardItemRequestValidationError{
					field:  "Position",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPosition()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateDashboardItemRequestValidationError{
				field:  "Position",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateDashboardItemRequestMultiError(errors)
	}

	return nil
}

// CreateDashboardItemRequestMultiError is an error wrapping multiple
// validation errors returned by CreateDashboardItemRequest.ValidateAll() if
// the designated constraints aren't met.
type CreateDashboardItemRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateDashboardItemRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateDashboardItemRequestMultiError) AllErrors() []error { return m }

// CreateDashboardItemRequestValidationError is the validation error returned
// by CreateDashboardItemRequest.Validate if the designated constraints aren't met.
type CreateDashboardItemRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateDashboardItemRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateDashboardItemRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateDashboardItemRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateDashboardItemRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateDashboardItemRequestValidationError) ErrorName() string {
	return "CreateDashboardItemRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateDashboardItemRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateDashboardItemRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateDashboardItemRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateDashboardItemRequestValidationError{}

// Validate checks the field values on UpdateDashboardItemRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateDashboardItemRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateDashboardItemRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateDashboardItemRequestMultiError, or nil if none found.
func (m *UpdateDashboardItemRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateDashboardItemRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectId

	// no validation rules for DashboardId

	// no validation rules for ItemId

	if all {
		switch v := interface{}(m.GetQuery()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateDashboardItemRequestValidationError{
					field:  "Query",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateDashboardItemRequestValidationError{
					field:  "Query",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetQuery()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateDashboardItemRequestValidationError{
				field:  "Query",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetPosition()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateDashboardItemRequestValidationError{
					field:  "Position",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateDashboardItemRequestValidationError{
					field:  "Position",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPosition()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateDashboardItemRequestValidationError{
				field:  "Position",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.Name != nil {
		// no validation rules for Name
	}

	if m.Type != nil {
		// no validation rules for Type
	}

	if len(errors) > 0 {
		return UpdateDashboardItemRequestMultiError(errors)
	}

	return nil
}

// UpdateDashboardItemRequestMultiError is an error wrapping multiple
// validation errors returned by UpdateDashboardItemRequest.ValidateAll() if
// the designated constraints aren't met.
type UpdateDashboardItemRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateDashboardItemRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateDashboardItemRequestMultiError) AllErrors() []error { return m }

// UpdateDashboardItemRequestValidationError is the validation error returned
// by UpdateDashboardItemRequest.Validate if the designated constraints aren't met.
type UpdateDashboardItemRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateDashboardItemRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateDashboardItemRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateDashboardItemRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateDashboardItemRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateDashboardItemRequestValidationError) ErrorName() string {
	return "UpdateDashboardItemRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateDashboardItemRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateDashboardItemRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateDashboardItemRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateDashboardItemRequestValidationError{}

// Validate checks the field values on DeleteDashboardItemRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteDashboardItemRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteDashboardItemRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteDashboardItemRequestMultiError, or nil if none found.
func (m *DeleteDashboardItemRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteDashboardItemRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectId

	// no validation rules for DashboardId

	// no validation rules for ItemId

	if len(errors) > 0 {
		return DeleteDashboardItemRequestMultiError(errors)
	}

	return nil
}

// DeleteDashboardItemRequestMultiError is an error wrapping multiple
// validation errors returned by DeleteDashboardItemRequest.ValidateAll() if
// the designated constraints aren't met.
type DeleteDashboardItemRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteDashboardItemRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteDashboardItemRequestMultiError) AllErrors() []error { return m }

// DeleteDashboardItemRequestValidationError is the validation error returned
// by DeleteDashboardItemRequest.Validate if the designated constraints aren't met.
type DeleteDashboardItemRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteDashboardItemRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteDashboardItemRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteDashboardItemRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteDashboardItemRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteDashboardItemRequestValidationError) ErrorName() string {
	return "DeleteDashboardItemRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteDashboardItemRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteDashboardItemRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteDashboardItemRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteDashboardItemRequestValidationError{}

// Validate checks the field values on DeleteDashboardItemResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteDashboardItemResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteDashboardItemResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteDashboardItemResponseMultiError, or nil if none found.
func (m *DeleteDashboardItemResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteDashboardItemResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteDashboardItemResponseMultiError(errors)
	}

	return nil
}

// DeleteDashboardItemResponseMultiError is an error wrapping multiple
// validation errors returned by DeleteDashboardItemResponse.ValidateAll() if
// the designated constraints aren't met.
type DeleteDashboardItemResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteDashboardItemResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteDashboardItemResponseMultiError) AllErrors() []error { return m }

// DeleteDashboardItemResponseValidationError is the validation error returned
// by DeleteDashboardItemResponse.Validate if the designated constraints
// aren't met.
type DeleteDashboardItemResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteDashboardItemResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteDashboardItemResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteDashboardItemResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteDashboardItemResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteDashboardItemResponseValidationError) ErrorName() string {
	return "DeleteDashboardItemResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteDashboardItemResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteDashboardItemResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteDashboardItemResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteDashboardItemResponseValidationError{}
