// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/openclick/v1/ingest.proto

package openclick_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on RegisterDeviceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RegisterDeviceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterDeviceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterDeviceRequestMultiError, or nil if none found.
func (m *RegisterDeviceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterDeviceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetProperties()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RegisterDeviceRequestValidationError{
					field:  "Properties",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RegisterDeviceRequestValidationError{
					field:  "Properties",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProperties()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RegisterDeviceRequestValidationError{
				field:  "Properties",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.ApiKey != nil {
		// no validation rules for ApiKey
	}

	if len(errors) > 0 {
		return RegisterDeviceRequestMultiError(errors)
	}

	return nil
}

// RegisterDeviceRequestMultiError is an error wrapping multiple validation
// errors returned by RegisterDeviceRequest.ValidateAll() if the designated
// constraints aren't met.
type RegisterDeviceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterDeviceRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterDeviceRequestMultiError) AllErrors() []error { return m }

// RegisterDeviceRequestValidationError is the validation error returned by
// RegisterDeviceRequest.Validate if the designated constraints aren't met.
type RegisterDeviceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterDeviceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterDeviceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterDeviceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterDeviceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterDeviceRequestValidationError) ErrorName() string {
	return "RegisterDeviceRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterDeviceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterDeviceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterDeviceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterDeviceRequestValidationError{}

// Validate checks the field values on RegisterDeviceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RegisterDeviceResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterDeviceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterDeviceResponseMultiError, or nil if none found.
func (m *RegisterDeviceResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterDeviceResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DeviceId

	if len(errors) > 0 {
		return RegisterDeviceResponseMultiError(errors)
	}

	return nil
}

// RegisterDeviceResponseMultiError is an error wrapping multiple validation
// errors returned by RegisterDeviceResponse.ValidateAll() if the designated
// constraints aren't met.
type RegisterDeviceResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterDeviceResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterDeviceResponseMultiError) AllErrors() []error { return m }

// RegisterDeviceResponseValidationError is the validation error returned by
// RegisterDeviceResponse.Validate if the designated constraints aren't met.
type RegisterDeviceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterDeviceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterDeviceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterDeviceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterDeviceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterDeviceResponseValidationError) ErrorName() string {
	return "RegisterDeviceResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterDeviceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterDeviceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterDeviceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterDeviceResponseValidationError{}

// Validate checks the field values on CaptureEventRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CaptureEventRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CaptureEventRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CaptureEventRequestMultiError, or nil if none found.
func (m *CaptureEventRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CaptureEventRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Event

	// no validation rules for DistinctId

	if all {
		switch v := interface{}(m.GetProperties()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CaptureEventRequestValidationError{
					field:  "Properties",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CaptureEventRequestValidationError{
					field:  "Properties",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProperties()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CaptureEventRequestValidationError{
				field:  "Properties",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.ApiKey != nil {
		// no validation rules for ApiKey
	}

	if m.Timestamp != nil {

		if all {
			switch v := interface{}(m.GetTimestamp()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CaptureEventRequestValidationError{
						field:  "Timestamp",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CaptureEventRequestValidationError{
						field:  "Timestamp",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetTimestamp()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CaptureEventRequestValidationError{
					field:  "Timestamp",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.SessionId != nil {
		// no validation rules for SessionId
	}

	if m.DeviceId != nil {
		// no validation rules for DeviceId
	}

	if len(errors) > 0 {
		return CaptureEventRequestMultiError(errors)
	}

	return nil
}

// CaptureEventRequestMultiError is an error wrapping multiple validation
// errors returned by CaptureEventRequest.ValidateAll() if the designated
// constraints aren't met.
type CaptureEventRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CaptureEventRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CaptureEventRequestMultiError) AllErrors() []error { return m }

// CaptureEventRequestValidationError is the validation error returned by
// CaptureEventRequest.Validate if the designated constraints aren't met.
type CaptureEventRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CaptureEventRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CaptureEventRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CaptureEventRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CaptureEventRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CaptureEventRequestValidationError) ErrorName() string {
	return "CaptureEventRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CaptureEventRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCaptureEventRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CaptureEventRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CaptureEventRequestValidationError{}

// Validate checks the field values on CaptureEventResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CaptureEventResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CaptureEventResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CaptureEventResponseMultiError, or nil if none found.
func (m *CaptureEventResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CaptureEventResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	if len(errors) > 0 {
		return CaptureEventResponseMultiError(errors)
	}

	return nil
}

// CaptureEventResponseMultiError is an error wrapping multiple validation
// errors returned by CaptureEventResponse.ValidateAll() if the designated
// constraints aren't met.
type CaptureEventResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CaptureEventResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CaptureEventResponseMultiError) AllErrors() []error { return m }

// CaptureEventResponseValidationError is the validation error returned by
// CaptureEventResponse.Validate if the designated constraints aren't met.
type CaptureEventResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CaptureEventResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CaptureEventResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CaptureEventResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CaptureEventResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CaptureEventResponseValidationError) ErrorName() string {
	return "CaptureEventResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CaptureEventResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCaptureEventResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CaptureEventResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CaptureEventResponseValidationError{}

// Validate checks the field values on BatchEvent with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BatchEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BatchEvent with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BatchEventMultiError, or
// nil if none found.
func (m *BatchEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *BatchEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Event

	// no validation rules for DistinctId

	if all {
		switch v := interface{}(m.GetProperties()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BatchEventValidationError{
					field:  "Properties",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BatchEventValidationError{
					field:  "Properties",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProperties()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BatchEventValidationError{
				field:  "Properties",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.Timestamp != nil {

		if all {
			switch v := interface{}(m.GetTimestamp()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, BatchEventValidationError{
						field:  "Timestamp",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, BatchEventValidationError{
						field:  "Timestamp",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetTimestamp()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return BatchEventValidationError{
					field:  "Timestamp",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.SessionId != nil {
		// no validation rules for SessionId
	}

	if m.DeviceId != nil {
		// no validation rules for DeviceId
	}

	if len(errors) > 0 {
		return BatchEventMultiError(errors)
	}

	return nil
}

// BatchEventMultiError is an error wrapping multiple validation errors
// returned by BatchEvent.ValidateAll() if the designated constraints aren't met.
type BatchEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BatchEventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BatchEventMultiError) AllErrors() []error { return m }

// BatchEventValidationError is the validation error returned by
// BatchEvent.Validate if the designated constraints aren't met.
type BatchEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BatchEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BatchEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BatchEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BatchEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BatchEventValidationError) ErrorName() string { return "BatchEventValidationError" }

// Error satisfies the builtin error interface
func (e BatchEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBatchEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BatchEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BatchEventValidationError{}

// Validate checks the field values on BatchCaptureRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BatchCaptureRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BatchCaptureRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BatchCaptureRequestMultiError, or nil if none found.
func (m *BatchCaptureRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BatchCaptureRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetBatch() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, BatchCaptureRequestValidationError{
						field:  fmt.Sprintf("Batch[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, BatchCaptureRequestValidationError{
						field:  fmt.Sprintf("Batch[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return BatchCaptureRequestValidationError{
					field:  fmt.Sprintf("Batch[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.ApiKey != nil {
		// no validation rules for ApiKey
	}

	if len(errors) > 0 {
		return BatchCaptureRequestMultiError(errors)
	}

	return nil
}

// BatchCaptureRequestMultiError is an error wrapping multiple validation
// errors returned by BatchCaptureRequest.ValidateAll() if the designated
// constraints aren't met.
type BatchCaptureRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BatchCaptureRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BatchCaptureRequestMultiError) AllErrors() []error { return m }

// BatchCaptureRequestValidationError is the validation error returned by
// BatchCaptureRequest.Validate if the designated constraints aren't met.
type BatchCaptureRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BatchCaptureRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BatchCaptureRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BatchCaptureRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BatchCaptureRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BatchCaptureRequestValidationError) ErrorName() string {
	return "BatchCaptureRequestValidationError"
}

// Error satisfies the builtin error interface
func (e BatchCaptureRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBatchCaptureRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BatchCaptureRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BatchCaptureRequestValidationError{}

// Validate checks the field values on BatchCaptureResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BatchCaptureResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BatchCaptureResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BatchCaptureResponseMultiError, or nil if none found.
func (m *BatchCaptureResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *BatchCaptureResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	// no validation rules for Count

	if len(errors) > 0 {
		return BatchCaptureResponseMultiError(errors)
	}

	return nil
}

// BatchCaptureResponseMultiError is an error wrapping multiple validation
// errors returned by BatchCaptureResponse.ValidateAll() if the designated
// constraints aren't met.
type BatchCaptureResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BatchCaptureResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BatchCaptureResponseMultiError) AllErrors() []error { return m }

// BatchCaptureResponseValidationError is the validation error returned by
// BatchCaptureResponse.Validate if the designated constraints aren't met.
type BatchCaptureResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BatchCaptureResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BatchCaptureResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BatchCaptureResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BatchCaptureResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BatchCaptureResponseValidationError) ErrorName() string {
	return "BatchCaptureResponseValidationError"
}

// Error satisfies the builtin error interface
func (e BatchCaptureResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBatchCaptureResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BatchCaptureResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BatchCaptureResponseValidationError{}

// Validate checks the field values on IdentifyRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *IdentifyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IdentifyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IdentifyRequestMultiError, or nil if none found.
func (m *IdentifyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *IdentifyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DistinctId

	if all {
		switch v := interface{}(m.GetProperties()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, IdentifyRequestValidationError{
					field:  "Properties",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, IdentifyRequestValidationError{
					field:  "Properties",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProperties()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return IdentifyRequestValidationError{
				field:  "Properties",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.ApiKey != nil {
		// no validation rules for ApiKey
	}

	if len(errors) > 0 {
		return IdentifyRequestMultiError(errors)
	}

	return nil
}

// IdentifyRequestMultiError is an error wrapping multiple validation errors
// returned by IdentifyRequest.ValidateAll() if the designated constraints
// aren't met.
type IdentifyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IdentifyRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IdentifyRequestMultiError) AllErrors() []error { return m }

// IdentifyRequestValidationError is the validation error returned by
// IdentifyRequest.Validate if the designated constraints aren't met.
type IdentifyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IdentifyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IdentifyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IdentifyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IdentifyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IdentifyRequestValidationError) ErrorName() string { return "IdentifyRequestValidationError" }

// Error satisfies the builtin error interface
func (e IdentifyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIdentifyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IdentifyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IdentifyRequestValidationError{}

// Validate checks the field values on IdentifyResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *IdentifyResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IdentifyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IdentifyResponseMultiError, or nil if none found.
func (m *IdentifyResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *IdentifyResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	if len(errors) > 0 {
		return IdentifyResponseMultiError(errors)
	}

	return nil
}

// IdentifyResponseMultiError is an error wrapping multiple validation errors
// returned by IdentifyResponse.ValidateAll() if the designated constraints
// aren't met.
type IdentifyResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IdentifyResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IdentifyResponseMultiError) AllErrors() []error { return m }

// IdentifyResponseValidationError is the validation error returned by
// IdentifyResponse.Validate if the designated constraints aren't met.
type IdentifyResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IdentifyResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IdentifyResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IdentifyResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IdentifyResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IdentifyResponseValidationError) ErrorName() string { return "IdentifyResponseValidationError" }

// Error satisfies the builtin error interface
func (e IdentifyResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIdentifyResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IdentifyResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IdentifyResponseValidationError{}

// Validate checks the field values on AliasRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AliasRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AliasRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AliasRequestMultiError, or
// nil if none found.
func (m *AliasRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AliasRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Alias

	// no validation rules for DistinctId

	if m.ApiKey != nil {
		// no validation rules for ApiKey
	}

	if len(errors) > 0 {
		return AliasRequestMultiError(errors)
	}

	return nil
}

// AliasRequestMultiError is an error wrapping multiple validation errors
// returned by AliasRequest.ValidateAll() if the designated constraints aren't met.
type AliasRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AliasRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AliasRequestMultiError) AllErrors() []error { return m }

// AliasRequestValidationError is the validation error returned by
// AliasRequest.Validate if the designated constraints aren't met.
type AliasRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AliasRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AliasRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AliasRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AliasRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AliasRequestValidationError) ErrorName() string { return "AliasRequestValidationError" }

// Error satisfies the builtin error interface
func (e AliasRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAliasRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AliasRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AliasRequestValidationError{}

// Validate checks the field values on AliasResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AliasResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AliasResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AliasResponseMultiError, or
// nil if none found.
func (m *AliasResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AliasResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	if len(errors) > 0 {
		return AliasResponseMultiError(errors)
	}

	return nil
}

// AliasResponseMultiError is an error wrapping multiple validation errors
// returned by AliasResponse.ValidateAll() if the designated constraints
// aren't met.
type AliasResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AliasResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AliasResponseMultiError) AllErrors() []error { return m }

// AliasResponseValidationError is the validation error returned by
// AliasResponse.Validate if the designated constraints aren't met.
type AliasResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AliasResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AliasResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AliasResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AliasResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AliasResponseValidationError) ErrorName() string { return "AliasResponseValidationError" }

// Error satisfies the builtin error interface
func (e AliasResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAliasResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AliasResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AliasResponseValidationError{}

// Validate checks the field values on IngestReplayRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *IngestReplayRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IngestReplayRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IngestReplayRequestMultiError, or nil if none found.
func (m *IngestReplayRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *IngestReplayRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SessionId

	// no validation rules for DistinctId

	// no validation rules for ChunkIndex

	// no validation rules for Data

	// no validation rules for Metadata

	if m.ApiKey != nil {
		// no validation rules for ApiKey
	}

	if len(errors) > 0 {
		return IngestReplayRequestMultiError(errors)
	}

	return nil
}

// IngestReplayRequestMultiError is an error wrapping multiple validation
// errors returned by IngestReplayRequest.ValidateAll() if the designated
// constraints aren't met.
type IngestReplayRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IngestReplayRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IngestReplayRequestMultiError) AllErrors() []error { return m }

// IngestReplayRequestValidationError is the validation error returned by
// IngestReplayRequest.Validate if the designated constraints aren't met.
type IngestReplayRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IngestReplayRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IngestReplayRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IngestReplayRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IngestReplayRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IngestReplayRequestValidationError) ErrorName() string {
	return "IngestReplayRequestValidationError"
}

// Error satisfies the builtin error interface
func (e IngestReplayRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIngestReplayRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IngestReplayRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IngestReplayRequestValidationError{}

// Validate checks the field values on IngestReplayResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *IngestReplayResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IngestReplayResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IngestReplayResponseMultiError, or nil if none found.
func (m *IngestReplayResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *IngestReplayResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	if len(errors) > 0 {
		return IngestReplayResponseMultiError(errors)
	}

	return nil
}

// IngestReplayResponseMultiError is an error wrapping multiple validation
// errors returned by IngestReplayResponse.ValidateAll() if the designated
// constraints aren't met.
type IngestReplayResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IngestReplayResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IngestReplayResponseMultiError) AllErrors() []error { return m }

// IngestReplayResponseValidationError is the validation error returned by
// IngestReplayResponse.Validate if the designated constraints aren't met.
type IngestReplayResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IngestReplayResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IngestReplayResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IngestReplayResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IngestReplayResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IngestReplayResponseValidationError) ErrorName() string {
	return "IngestReplayResponseValidationError"
}

// Error satisfies the builtin error interface
func (e IngestReplayResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIngestReplayResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IngestReplayResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IngestReplayResponseValidationError{}
