// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/openclick/v1/openclick.proto

package openclick_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BaseService_Ping_FullMethodName                = "/v1.BaseService/Ping"
	BaseService_ListPermissions_FullMethodName     = "/v1.BaseService/ListPermissions"
	BaseService_ListProjects_FullMethodName        = "/v1.BaseService/ListProjects"
	BaseService_CreateProject_FullMethodName       = "/v1.BaseService/CreateProject"
	BaseService_GetProject_FullMethodName          = "/v1.BaseService/GetProject"
	BaseService_UpdateProject_FullMethodName       = "/v1.BaseService/UpdateProject"
	BaseService_DeleteProject_FullMethodName       = "/v1.BaseService/DeleteProject"
	BaseService_AddMember_FullMethodName           = "/v1.BaseService/AddMember"
	BaseService_RemoveMember_FullMethodName        = "/v1.BaseService/RemoveMember"
	BaseService_ListDashboards_FullMethodName      = "/v1.BaseService/ListDashboards"
	BaseService_CreateDashboard_FullMethodName     = "/v1.BaseService/CreateDashboard"
	BaseService_GetDashboard_FullMethodName        = "/v1.BaseService/GetDashboard"
	BaseService_DeleteDashboard_FullMethodName     = "/v1.BaseService/DeleteDashboard"
	BaseService_CreateDashboardItem_FullMethodName = "/v1.BaseService/CreateDashboardItem"
	BaseService_UpdateDashboardItem_FullMethodName = "/v1.BaseService/UpdateDashboardItem"
	BaseService_DeleteDashboardItem_FullMethodName = "/v1.BaseService/DeleteDashboardItem"
	BaseService_QueryTrends_FullMethodName         = "/v1.BaseService/QueryTrends"
	BaseService_QueryFunnel_FullMethodName         = "/v1.BaseService/QueryFunnel"
	BaseService_QueryRetention_FullMethodName      = "/v1.BaseService/QueryRetention"
	BaseService_QueryPaths_FullMethodName          = "/v1.BaseService/QueryPaths"
	BaseService_QueryEvents_FullMethodName         = "/v1.BaseService/QueryEvents"
	BaseService_ListEventNames_FullMethodName      = "/v1.BaseService/ListEventNames"
	BaseService_ListSessions_FullMethodName        = "/v1.BaseService/ListSessions"
	BaseService_GetSession_FullMethodName          = "/v1.BaseService/GetSession"
	BaseService_GetSessionChunks_FullMethodName    = "/v1.BaseService/GetSessionChunks"
	BaseService_DeleteSession_FullMethodName       = "/v1.BaseService/DeleteSession"
	BaseService_ListPersons_FullMethodName         = "/v1.BaseService/ListPersons"
	BaseService_GetPerson_FullMethodName           = "/v1.BaseService/GetPerson"
	BaseService_DeletePerson_FullMethodName        = "/v1.BaseService/DeletePerson"
	BaseService_ListCohorts_FullMethodName         = "/v1.BaseService/ListCohorts"
	BaseService_CreateCohort_FullMethodName        = "/v1.BaseService/CreateCohort"
	BaseService_DeleteCohort_FullMethodName        = "/v1.BaseService/DeleteCohort"
	BaseService_ListFeatureFlags_FullMethodName    = "/v1.BaseService/ListFeatureFlags"
	BaseService_CreateFeatureFlag_FullMethodName   = "/v1.BaseService/CreateFeatureFlag"
	BaseService_UpdateFeatureFlag_FullMethodName   = "/v1.BaseService/UpdateFeatureFlag"
	BaseService_DeleteFeatureFlag_FullMethodName   = "/v1.BaseService/DeleteFeatureFlag"
	BaseService_EvaluateFlags_FullMethodName       = "/v1.BaseService/EvaluateFlags"
	BaseService_Decide_FullMethodName              = "/v1.BaseService/Decide"
	BaseService_CaptureEvent_FullMethodName        = "/v1.BaseService/CaptureEvent"
	BaseService_BatchCapture_FullMethodName        = "/v1.BaseService/BatchCapture"
	BaseService_Identify_FullMethodName            = "/v1.BaseService/Identify"
	BaseService_Alias_FullMethodName               = "/v1.BaseService/Alias"
	BaseService_IngestReplay_FullMethodName        = "/v1.BaseService/IngestReplay"
)

// BaseServiceClient is the client API for BaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BaseServiceClient interface {
	// Ping is a simple GET request that returns a Pong message.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Permissions
	ListPermissions(ctx context.Context, in *ListPermissionsRequest, opts ...grpc.CallOption) (*ListPermissionsResponse, error)
	// Projects
	ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error)
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error)
	GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*GetProjectResponse, error)
	UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error)
	DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*DeleteProjectResponse, error)
	AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*AddMemberResponse, error)
	RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*RemoveMemberResponse, error)
	// Dashboards
	ListDashboards(ctx context.Context, in *ListDashboardsRequest, opts ...grpc.CallOption) (*ListDashboardsResponse, error)
	CreateDashboard(ctx context.Context, in *CreateDashboardRequest, opts ...grpc.CallOption) (*DashboardResponse, error)
	GetDashboard(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardResponse, error)
	DeleteDashboard(ctx context.Context, in *DeleteDashboardRequest, opts ...grpc.CallOption) (*DeleteDashboardResponse, error)
	CreateDashboardItem(ctx context.Context, in *CreateDashboardItemRequest, opts ...grpc.CallOption) (*DashboardItemResponse, error)
	UpdateDashboardItem(ctx context.Context, in *UpdateDashboardItemRequest, opts ...grpc.CallOption) (*DashboardItemResponse, error)
	DeleteDashboardItem(ctx context.Context, in *DeleteDashboardItemRequest, opts ...grpc.CallOption) (*DeleteDashboardItemResponse, error)
	// Analytics
	QueryTrends(ctx context.Context, in *QueryTrendsRequest, opts ...grpc.CallOption) (*QueryTrendsResponse, error)
	QueryFunnel(ctx context.Context, in *QueryFunnelRequest, opts ...grpc.CallOption) (*QueryFunnelResponse, error)
	QueryRetention(ctx context.Context, in *QueryRetentionRequest, opts ...grpc.CallOption) (*QueryRetentionResponse, error)
	QueryPaths(ctx context.Context, in *QueryPathsRequest, opts ...grpc.CallOption) (*QueryPathsResponse, error)
	QueryEvents(ctx context.Context, in *QueryEventsRequest, opts ...grpc.CallOption) (*QueryEventsResponse, error)
	ListEventNames(ctx context.Context, in *ListEventNamesRequest, opts ...grpc.CallOption) (*ListEventNamesResponse, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	GetSessionChunks(ctx context.Context, in *GetSessionChunksRequest, opts ...grpc.CallOption) (*GetSessionChunksResponse, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
	// Persons & Cohorts
	ListPersons(ctx context.Context, in *ListPersonsRequest, opts ...grpc.CallOption) (*ListPersonsResponse, error)
	GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*GetPersonResponse, error)
	DeletePerson(ctx context.Context, in *DeletePersonRequest, opts ...grpc.CallOption) (*DeletePersonResponse, error)
	ListCohorts(ctx context.Context, in *ListCohortsRequest, opts ...grpc.CallOption) (*ListCohortsResponse, error)
	CreateCohort(ctx context.Context, in *CreateCohortRequest, opts ...grpc.CallOption) (*CohortResponse, error)
	DeleteCohort(ctx context.Context, in *DeleteCohortRequest, opts ...grpc.CallOption) (*DeleteCohortResponse, error)
	// Feature Flags
	ListFeatureFlags(ctx context.Context, in *ListFeatureFlagsRequest, opts ...grpc.CallOption) (*ListFeatureFlagsResponse, error)
	CreateFeatureFlag(ctx context.Context, in *CreateFeatureFlagRequest, opts ...grpc.CallOption) (*FeatureFlagResponse, error)
	UpdateFeatureFlag(ctx context.Context, in *UpdateFeatureFlagRequest, opts ...grpc.CallOption) (*FeatureFlagResponse, error)
	DeleteFeatureFlag(ctx context.Context, in *DeleteFeatureFlagRequest, opts ...grpc.CallOption) (*DeleteFeatureFlagResponse, error)
	EvaluateFlags(ctx context.Context, in *EvaluateFlagsRequest, opts ...grpc.CallOption) (*EvaluateFlagsResponse, error)
	Decide(ctx context.Context, in *DecideRequest, opts ...grpc.CallOption) (*DecideResponse, error)
	// Ingestion
	CaptureEvent(ctx context.Context, in *CaptureEventRequest, opts ...grpc.CallOption) (*CaptureEventResponse, error)
	BatchCapture(ctx context.Context, in *BatchCaptureRequest, opts ...grpc.CallOption) (*BatchCaptureResponse, error)
	Identify(ctx context.Context, in *IdentifyRequest, opts ...grpc.CallOption) (*IdentifyResponse, error)
	Alias(ctx context.Context, in *AliasRequest, opts ...grpc.CallOption) (*AliasResponse, error)
	IngestReplay(ctx context.Context, in *IngestReplayRequest, opts ...grpc.CallOption) (*IngestReplayResponse, error)
}

type baseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBaseServiceClient(cc grpc.ClientConnInterface) BaseServiceClient {
	return &baseServiceClient{cc}
}

func (c *baseServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, BaseService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) ListPermissions(ctx context.Context, in *ListPermissionsRequest, opts ...grpc.CallOption) (*ListPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPermissionsResponse)
	err := c.cc.Invoke(ctx, BaseService_ListPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectsResponse)
	err := c.cc.Invoke(ctx, BaseService_ListProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectResponse)
	err := c.cc.Invoke(ctx, BaseService_CreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*GetProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProjectResponse)
	err := c.cc.Invoke(ctx, BaseService_GetProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectResponse)
	err := c.cc.Invoke(ctx, BaseService_UpdateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*DeleteProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProjectResponse)
	err := c.cc.Invoke(ctx, BaseService_DeleteProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*AddMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMemberResponse)
	err := c.cc.Invoke(ctx, BaseService_AddMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*RemoveMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMemberResponse)
	err := c.cc.Invoke(ctx, BaseService_RemoveMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) ListDashboards(ctx context.Context, in *ListDashboardsRequest, opts ...grpc.CallOption) (*ListDashboardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDashboardsResponse)
	err := c.cc.Invoke(ctx, BaseService_ListDashboards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) CreateDashboard(ctx context.Context, in *CreateDashboardRequest, opts ...grpc.CallOption) (*DashboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DashboardResponse)
	err := c.cc.Invoke(ctx, BaseService_CreateDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) GetDashboard(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardResponse)
	err := c.cc.Invoke(ctx, BaseService_GetDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) DeleteDashboard(ctx context.Context, in *DeleteDashboardRequest, opts ...grpc.CallOption) (*DeleteDashboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDashboardResponse)
	err := c.cc.Invoke(ctx, BaseService_DeleteDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) CreateDashboardItem(ctx context.Context, in *CreateDashboardItemRequest, opts ...grpc.CallOption) (*DashboardItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DashboardItemResponse)
	err := c.cc.Invoke(ctx, BaseService_CreateDashboardItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) UpdateDashboardItem(ctx context.Context, in *UpdateDashboardItemRequest, opts ...grpc.CallOption) (*DashboardItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DashboardItemResponse)
	err := c.cc.Invoke(ctx, BaseService_UpdateDashboardItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) DeleteDashboardItem(ctx context.Context, in *DeleteDashboardItemRequest, opts ...grpc.CallOption) (*DeleteDashboardItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDashboardItemResponse)
	err := c.cc.Invoke(ctx, BaseService_DeleteDashboardItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) QueryTrends(ctx context.Context, in *QueryTrendsRequest, opts ...grpc.CallOption) (*QueryTrendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryTrendsResponse)
	err := c.cc.Invoke(ctx, BaseService_QueryTrends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) QueryFunnel(ctx context.Context, in *QueryFunnelRequest, opts ...grpc.CallOption) (*QueryFunnelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryFunnelResponse)
	err := c.cc.Invoke(ctx, BaseService_QueryFunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) QueryRetention(ctx context.Context, in *QueryRetentionRequest, opts ...grpc.CallOption) (*QueryRetentionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryRetentionResponse)
	err := c.cc.Invoke(ctx, BaseService_QueryRetention_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) QueryPaths(ctx context.Context, in *QueryPathsRequest, opts ...grpc.CallOption) (*QueryPathsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPathsResponse)
	err := c.cc.Invoke(ctx, BaseService_QueryPaths_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) QueryEvents(ctx context.Context, in *QueryEventsRequest, opts ...grpc.CallOption) (*QueryEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryEventsResponse)
	err := c.cc.Invoke(ctx, BaseService_QueryEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) ListEventNames(ctx context.Context, in *ListEventNamesRequest, opts ...grpc.CallOption) (*ListEventNamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventNamesResponse)
	err := c.cc.Invoke(ctx, BaseService_ListEventNames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, BaseService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, BaseService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) GetSessionChunks(ctx context.Context, in *GetSessionChunksRequest, opts ...grpc.CallOption) (*GetSessionChunksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionChunksResponse)
	err := c.cc.Invoke(ctx, BaseService_GetSessionChunks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, BaseService_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) ListPersons(ctx context.Context, in *ListPersonsRequest, opts ...grpc.CallOption) (*ListPersonsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPersonsResponse)
	err := c.cc.Invoke(ctx, BaseService_ListPersons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) GetPerson(ctx context.Context, in *GetPersonRequest, opts ...grpc.CallOption) (*GetPersonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPersonResponse)
	err := c.cc.Invoke(ctx, BaseService_GetPerson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) DeletePerson(ctx context.Context, in *DeletePersonRequest, opts ...grpc.CallOption) (*DeletePersonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePersonResponse)
	err := c.cc.Invoke(ctx, BaseService_DeletePerson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) ListCohorts(ctx context.Context, in *ListCohortsRequest, opts ...grpc.CallOption) (*ListCohortsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCohortsResponse)
	err := c.cc.Invoke(ctx, BaseService_ListCohorts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) CreateCohort(ctx context.Context, in *CreateCohortRequest, opts ...grpc.CallOption) (*CohortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CohortResponse)
	err := c.cc.Invoke(ctx, BaseService_CreateCohort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) DeleteCohort(ctx context.Context, in *DeleteCohortRequest, opts ...grpc.CallOption) (*DeleteCohortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCohortResponse)
	err := c.cc.Invoke(ctx, BaseService_DeleteCohort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) ListFeatureFlags(ctx context.Context, in *ListFeatureFlagsRequest, opts ...grpc.CallOption) (*ListFeatureFlagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFeatureFlagsResponse)
	err := c.cc.Invoke(ctx, BaseService_ListFeatureFlags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) CreateFeatureFlag(ctx context.Context, in *CreateFeatureFlagRequest, opts ...grpc.CallOption) (*FeatureFlagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeatureFlagResponse)
	err := c.cc.Invoke(ctx, BaseService_CreateFeatureFlag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) UpdateFeatureFlag(ctx context.Context, in *UpdateFeatureFlagRequest, opts ...grpc.CallOption) (*FeatureFlagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeatureFlagResponse)
	err := c.cc.Invoke(ctx, BaseService_UpdateFeatureFlag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) DeleteFeatureFlag(ctx context.Context, in *DeleteFeatureFlagRequest, opts ...grpc.CallOption) (*DeleteFeatureFlagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFeatureFlagResponse)
	err := c.cc.Invoke(ctx, BaseService_DeleteFeatureFlag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) EvaluateFlags(ctx context.Context, in *EvaluateFlagsRequest, opts ...grpc.CallOption) (*EvaluateFlagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateFlagsResponse)
	err := c.cc.Invoke(ctx, BaseService_EvaluateFlags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) Decide(ctx context.Context, in *DecideRequest, opts ...grpc.CallOption) (*DecideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecideResponse)
	err := c.cc.Invoke(ctx, BaseService_Decide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) CaptureEvent(ctx context.Context, in *CaptureEventRequest, opts ...grpc.CallOption) (*CaptureEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureEventResponse)
	err := c.cc.Invoke(ctx, BaseService_CaptureEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) BatchCapture(ctx context.Context, in *BatchCaptureRequest, opts ...grpc.CallOption) (*BatchCaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCaptureResponse)
	err := c.cc.Invoke(ctx, BaseService_BatchCapture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) Identify(ctx context.Context, in *IdentifyRequest, opts ...grpc.CallOption) (*IdentifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentifyResponse)
	err := c.cc.Invoke(ctx, BaseService_Identify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) Alias(ctx context.Context, in *AliasRequest, opts ...grpc.CallOption) (*AliasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AliasResponse)
	err := c.cc.Invoke(ctx, BaseService_Alias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) IngestReplay(ctx context.Context, in *IngestReplayRequest, opts ...grpc.CallOption) (*IngestReplayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestReplayResponse)
	err := c.cc.Invoke(ctx, BaseService_IngestReplay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaseServiceServer is the server API for BaseService service.
// All implementations must embed UnimplementedBaseServiceServer
// for forward compatibility.
type BaseServiceServer interface {
	// Ping is a simple GET request that returns a Pong message.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Permissions
	ListPermissions(context.Context, *ListPermissionsRequest) (*ListPermissionsResponse, error)
	// Projects
	ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error)
	CreateProject(context.Context, *CreateProjectRequest) (*ProjectResponse, error)
	GetProject(context.Context, *GetProjectRequest) (*GetProjectResponse, error)
	UpdateProject(context.Context, *UpdateProjectRequest) (*ProjectResponse, error)
	DeleteProject(context.Context, *DeleteProjectRequest) (*DeleteProjectResponse, error)
	AddMember(context.Context, *AddMemberRequest) (*AddMemberResponse, error)
	RemoveMember(context.Context, *RemoveMemberRequest) (*RemoveMemberResponse, error)
	// Dashboards
	ListDashboards(context.Context, *ListDashboardsRequest) (*ListDashboardsResponse, error)
	CreateDashboard(context.Context, *CreateDashboardRequest) (*DashboardResponse, error)
	GetDashboard(context.Context, *GetDashboardRequest) (*GetDashboardResponse, error)
	DeleteDashboard(context.Context, *DeleteDashboardRequest) (*DeleteDashboardResponse, error)
	CreateDashboardItem(context.Context, *CreateDashboardItemRequest) (*DashboardItemResponse, error)
	UpdateDashboardItem(context.Context, *UpdateDashboardItemRequest) (*DashboardItemResponse, error)
	DeleteDashboardItem(context.Context, *DeleteDashboardItemRequest) (*DeleteDashboardItemResponse, error)
	// Analytics
	QueryTrends(context.Context, *QueryTrendsRequest) (*QueryTrendsResponse, error)
	QueryFunnel(context.Context, *QueryFunnelRequest) (*QueryFunnelResponse, error)
	QueryRetention(context.Context, *QueryRetentionRequest) (*QueryRetentionResponse, error)
	QueryPaths(context.Context, *QueryPathsRequest) (*QueryPathsResponse, error)
	QueryEvents(context.Context, *QueryEventsRequest) (*QueryEventsResponse, error)
	ListEventNames(context.Context, *ListEventNamesRequest) (*ListEventNamesResponse, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*SessionResponse, error)
	GetSessionChunks(context.Context, *GetSessionChunksRequest) (*GetSessionChunksResponse, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	// Persons & Cohorts
	ListPersons(context.Context, *ListPersonsRequest) (*ListPersonsResponse, error)
	GetPerson(context.Context, *GetPersonRequest) (*GetPersonResponse, error)
	DeletePerson(context.Context, *DeletePersonRequest) (*DeletePersonResponse, error)
	ListCohorts(context.Context, *ListCohortsRequest) (*ListCohortsResponse, error)
	CreateCohort(context.Context, *CreateCohortRequest) (*CohortResponse, error)
	DeleteCohort(context.Context, *DeleteCohortRequest) (*DeleteCohortResponse, error)
	// Feature Flags
	ListFeatureFlags(context.Context, *ListFeatureFlagsRequest) (*ListFeatureFlagsResponse, error)
	CreateFeatureFlag(context.Context, *CreateFeatureFlagRequest) (*FeatureFlagResponse, error)
	UpdateFeatureFlag(context.Context, *UpdateFeatureFlagRequest) (*FeatureFlagResponse, error)
	DeleteFeatureFlag(context.Context, *DeleteFeatureFlagRequest) (*DeleteFeatureFlagResponse, error)
	EvaluateFlags(context.Context, *EvaluateFlagsRequest) (*EvaluateFlagsResponse, error)
	Decide(context.Context, *DecideRequest) (*DecideResponse, error)
	// Ingestion
	CaptureEvent(context.Context, *CaptureEventRequest) (*CaptureEventResponse, error)
	BatchCapture(context.Context, *BatchCaptureRequest) (*BatchCaptureResponse, error)
	Identify(context.Context, *IdentifyRequest) (*IdentifyResponse, error)
	Alias(context.Context, *AliasRequest) (*AliasResponse, error)
	IngestReplay(context.Context, *IngestReplayRequest) (*IngestReplayResponse, error)
	mustEmbedUnimplementedBaseServiceServer()
}

// UnimplementedBaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBaseServiceServer struct{}

func (UnimplementedBaseServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedBaseServiceServer) ListPermissions(context.Context, *ListPermissionsRequest) (*ListPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPermissions not implemented")
}
func (UnimplementedBaseServiceServer) ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedBaseServiceServer) CreateProject(context.Context, *CreateProjectRequest) (*ProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProject not implemented")
}
func (UnimplementedBaseServiceServer) GetProject(context.Context, *GetProjectRequest) (*GetProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProject not implemented")
}
func (UnimplementedBaseServiceServer) UpdateProject(context.Context, *UpdateProjectRequest) (*ProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProject not implemented")
}
func (UnimplementedBaseServiceServer) DeleteProject(context.Context, *DeleteProjectRequest) (*DeleteProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProject not implemented")
}
func (UnimplementedBaseServiceServer) AddMember(context.Context, *AddMemberRequest) (*AddMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMember not implemented")
}
func (UnimplementedBaseServiceServer) RemoveMember(context.Context, *RemoveMemberRequest) (*RemoveMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveMember not implemented")
}
func (UnimplementedBaseServiceServer) ListDashboards(context.Context, *ListDashboardsRequest) (*ListDashboardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDashboards not implemented")
}
func (UnimplementedBaseServiceServer) CreateDashboard(context.Context, *CreateDashboardRequest) (*DashboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDashboard not implemented")
}
func (UnimplementedBaseServiceServer) GetDashboard(context.Context, *GetDashboardRequest) (*GetDashboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDashboard not implemented")
}
func (UnimplementedBaseServiceServer) DeleteDashboard(context.Context, *DeleteDashboardRequest) (*DeleteDashboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDashboard not implemented")
}
func (UnimplementedBaseServiceServer) CreateDashboardItem(context.Context, *CreateDashboardItemRequest) (*DashboardItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDashboardItem not implemented")
}
func (UnimplementedBaseServiceServer) UpdateDashboardItem(context.Context, *UpdateDashboardItemRequest) (*DashboardItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDashboardItem not implemented")
}
func (UnimplementedBaseServiceServer) DeleteDashboardItem(context.Context, *DeleteDashboardItemRequest) (*DeleteDashboardItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDashboardItem not implemented")
}
func (UnimplementedBaseServiceServer) QueryTrends(context.Context, *QueryTrendsRequest) (*QueryTrendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryTrends not implemented")
}
func (UnimplementedBaseServiceServer) QueryFunnel(context.Context, *QueryFunnelRequest) (*QueryFunnelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryFunnel not implemented")
}
func (UnimplementedBaseServiceServer) QueryRetention(context.Context, *QueryRetentionRequest) (*QueryRetentionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryRetention not implemented")
}
func (UnimplementedBaseServiceServer) QueryPaths(context.Context, *QueryPathsRequest) (*QueryPathsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryPaths not implemented")
}
func (UnimplementedBaseServiceServer) QueryEvents(context.Context, *QueryEventsRequest) (*QueryEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryEvents not implemented")
}
func (UnimplementedBaseServiceServer) ListEventNames(context.Context, *ListEventNamesRequest) (*ListEventNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEventNames not implemented")
}
func (UnimplementedBaseServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedBaseServiceServer) GetSession(context.Context, *GetSessionRequest) (*SessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedBaseServiceServer) GetSessionChunks(context.Context, *GetSessionChunksRequest) (*GetSessionChunksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionChunks not implemented")
}
func (UnimplementedBaseServiceServer) DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedBaseServiceServer) ListPersons(context.Context, *ListPersonsRequest) (*ListPersonsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPersons not implemented")
}
func (UnimplementedBaseServiceServer) GetPerson(context.Context, *GetPersonRequest) (*GetPersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPerson not implemented")
}
func (UnimplementedBaseServiceServer) DeletePerson(context.Context, *DeletePersonRequest) (*DeletePersonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePerson not implemented")
}
func (UnimplementedBaseServiceServer) ListCohorts(context.Context, *ListCohortsRequest) (*ListCohortsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCohorts not implemented")
}
func (UnimplementedBaseServiceServer) CreateCohort(context.Context, *CreateCohortRequest) (*CohortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCohort not implemented")
}
func (UnimplementedBaseServiceServer) DeleteCohort(context.Context, *DeleteCohortRequest) (*DeleteCohortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCohort not implemented")
}
func (UnimplementedBaseServiceServer) ListFeatureFlags(context.Context, *ListFeatureFlagsRequest) (*ListFeatureFlagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFeatureFlags not implemented")
}
func (UnimplementedBaseServiceServer) CreateFeatureFlag(context.Context, *CreateFeatureFlagRequest) (*FeatureFlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFeatureFlag not implemented")
}
func (UnimplementedBaseServiceServer) UpdateFeatureFlag(context.Context, *UpdateFeatureFlagRequest) (*FeatureFlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFeatureFlag not implemented")
}
func (UnimplementedBaseServiceServer) DeleteFeatureFlag(context.Context, *DeleteFeatureFlagRequest) (*DeleteFeatureFlagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFeatureFlag not implemented")
}
func (UnimplementedBaseServiceServer) EvaluateFlags(context.Context, *EvaluateFlagsRequest) (*EvaluateFlagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateFlags not implemented")
}
func (UnimplementedBaseServiceServer) Decide(context.Context, *DecideRequest) (*DecideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decide not implemented")
}
func (UnimplementedBaseServiceServer) CaptureEvent(context.Context, *CaptureEventRequest) (*CaptureEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CaptureEvent not implemented")
}
func (UnimplementedBaseServiceServer) BatchCapture(context.Context, *BatchCaptureRequest) (*BatchCaptureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchCapture not implemented")
}
func (UnimplementedBaseServiceServer) Identify(context.Context, *IdentifyRequest) (*IdentifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Identify not implemented")
}
func (UnimplementedBaseServiceServer) Alias(context.Context, *AliasRequest) (*AliasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Alias not implemented")
}
func (UnimplementedBaseServiceServer) IngestReplay(context.Context, *IngestReplayRequest) (*IngestReplayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngestReplay not implemented")
}
func (UnimplementedBaseServiceServer) mustEmbedUnimplementedBaseServiceServer() {}
func (UnimplementedBaseServiceServer) testEmbeddedByValue()                     {}

// UnsafeBaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaseServiceServer will
// result in compilation errors.
type UnsafeBaseServiceServer interface {
	mustEmbedUnimplementedBaseServiceServer()
}

func RegisterBaseServiceServer(s grpc.ServiceRegistrar, srv BaseServiceServer) {
	// If the following call pancis, it indicates UnimplementedBaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BaseService_ServiceDesc, srv)
}

func _BaseService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_ListPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).ListPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_ListPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).ListPermissions(ctx, req.(*ListPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_ListProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).ListProjects(ctx, req.(*ListProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_CreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_GetProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).GetProject(ctx, req.(*GetProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_UpdateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).UpdateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_UpdateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).UpdateProject(ctx, req.(*UpdateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_DeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).DeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_DeleteProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).DeleteProject(ctx, req.(*DeleteProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_AddMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).AddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_AddMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).AddMember(ctx, req.(*AddMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_RemoveMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).RemoveMember(ctx, req.(*RemoveMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_ListDashboards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDashboardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).ListDashboards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_ListDashboards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).ListDashboards(ctx, req.(*ListDashboardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_CreateDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).CreateDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_CreateDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).CreateDashboard(ctx, req.(*CreateDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_GetDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).GetDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_GetDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).GetDashboard(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_DeleteDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).DeleteDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_DeleteDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).DeleteDashboard(ctx, req.(*DeleteDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_CreateDashboardItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDashboardItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).CreateDashboardItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_CreateDashboardItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).CreateDashboardItem(ctx, req.(*CreateDashboardItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_UpdateDashboardItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDashboardItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).UpdateDashboardItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_UpdateDashboardItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).UpdateDashboardItem(ctx, req.(*UpdateDashboardItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_DeleteDashboardItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDashboardItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).DeleteDashboardItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_DeleteDashboardItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).DeleteDashboardItem(ctx, req.(*DeleteDashboardItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_QueryTrends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTrendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).QueryTrends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_QueryTrends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).QueryTrends(ctx, req.(*QueryTrendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_QueryFunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).QueryFunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_QueryFunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).QueryFunnel(ctx, req.(*QueryFunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_QueryRetention_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRetentionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).QueryRetention(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_QueryRetention_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).QueryRetention(ctx, req.(*QueryRetentionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_QueryPaths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPathsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).QueryPaths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_QueryPaths_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).QueryPaths(ctx, req.(*QueryPathsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_QueryEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).QueryEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_QueryEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).QueryEvents(ctx, req.(*QueryEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_ListEventNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).ListEventNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_ListEventNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).ListEventNames(ctx, req.(*ListEventNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_GetSessionChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionChunksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).GetSessionChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_GetSessionChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).GetSessionChunks(ctx, req.(*GetSessionChunksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_ListPersons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPersonsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).ListPersons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_ListPersons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).ListPersons(ctx, req.(*ListPersonsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_GetPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).GetPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_GetPerson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).GetPerson(ctx, req.(*GetPersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_DeletePerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePersonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).DeletePerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_DeletePerson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).DeletePerson(ctx, req.(*DeletePersonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_ListCohorts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCohortsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).ListCohorts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_ListCohorts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).ListCohorts(ctx, req.(*ListCohortsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_CreateCohort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCohortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).CreateCohort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_CreateCohort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).CreateCohort(ctx, req.(*CreateCohortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_DeleteCohort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCohortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).DeleteCohort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_DeleteCohort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).DeleteCohort(ctx, req.(*DeleteCohortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_ListFeatureFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFeatureFlagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).ListFeatureFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_ListFeatureFlags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).ListFeatureFlags(ctx, req.(*ListFeatureFlagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_CreateFeatureFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFeatureFlagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).CreateFeatureFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_CreateFeatureFlag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).CreateFeatureFlag(ctx, req.(*CreateFeatureFlagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_UpdateFeatureFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFeatureFlagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).UpdateFeatureFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_UpdateFeatureFlag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).UpdateFeatureFlag(ctx, req.(*UpdateFeatureFlagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_DeleteFeatureFlag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFeatureFlagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).DeleteFeatureFlag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_DeleteFeatureFlag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).DeleteFeatureFlag(ctx, req.(*DeleteFeatureFlagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_EvaluateFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateFlagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).EvaluateFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_EvaluateFlags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).EvaluateFlags(ctx, req.(*EvaluateFlagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_Decide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).Decide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_Decide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).Decide(ctx, req.(*DecideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_CaptureEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).CaptureEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_CaptureEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).CaptureEvent(ctx, req.(*CaptureEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_BatchCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).BatchCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_BatchCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).BatchCapture(ctx, req.(*BatchCaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_Identify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).Identify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_Identify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).Identify(ctx, req.(*IdentifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_Alias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).Alias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_Alias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).Alias(ctx, req.(*AliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_IngestReplay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestReplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).IngestReplay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_IngestReplay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).IngestReplay(ctx, req.(*IngestReplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BaseService_ServiceDesc is the grpc.ServiceDesc for BaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.BaseService",
	HandlerType: (*BaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _BaseService_Ping_Handler,
		},
		{
			MethodName: "ListPermissions",
			Handler:    _BaseService_ListPermissions_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _BaseService_ListProjects_Handler,
		},
		{
			MethodName: "CreateProject",
			Handler:    _BaseService_CreateProject_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _BaseService_GetProject_Handler,
		},
		{
			MethodName: "UpdateProject",
			Handler:    _BaseService_UpdateProject_Handler,
		},
		{
			MethodName: "DeleteProject",
			Handler:    _BaseService_DeleteProject_Handler,
		},
		{
			MethodName: "AddMember",
			Handler:    _BaseService_AddMember_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _BaseService_RemoveMember_Handler,
		},
		{
			MethodName: "ListDashboards",
			Handler:    _BaseService_ListDashboards_Handler,
		},
		{
			MethodName: "CreateDashboard",
			Handler:    _BaseService_CreateDashboard_Handler,
		},
		{
			MethodName: "GetDashboard",
			Handler:    _BaseService_GetDashboard_Handler,
		},
		{
			MethodName: "DeleteDashboard",
			Handler:    _BaseService_DeleteDashboard_Handler,
		},
		{
			MethodName: "CreateDashboardItem",
			Handler:    _BaseService_CreateDashboardItem_Handler,
		},
		{
			MethodName: "UpdateDashboardItem",
			Handler:    _BaseService_UpdateDashboardItem_Handler,
		},
		{
			MethodName: "DeleteDashboardItem",
			Handler:    _BaseService_DeleteDashboardItem_Handler,
		},
		{
			MethodName: "QueryTrends",
			Handler:    _BaseService_QueryTrends_Handler,
		},
		{
			MethodName: "QueryFunnel",
			Handler:    _BaseService_QueryFunnel_Handler,
		},
		{
			MethodName: "QueryRetention",
			Handler:    _BaseService_QueryRetention_Handler,
		},
		{
			MethodName: "QueryPaths",
			Handler:    _BaseService_QueryPaths_Handler,
		},
		{
			MethodName: "QueryEvents",
			Handler:    _BaseService_QueryEvents_Handler,
		},
		{
			MethodName: "ListEventNames",
			Handler:    _BaseService_ListEventNames_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _BaseService_ListSessions_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _BaseService_GetSession_Handler,
		},
		{
			MethodName: "GetSessionChunks",
			Handler:    _BaseService_GetSessionChunks_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _BaseService_DeleteSession_Handler,
		},
		{
			MethodName: "ListPersons",
			Handler:    _BaseService_ListPersons_Handler,
		},
		{
			MethodName: "GetPerson",
			Handler:    _BaseService_GetPerson_Handler,
		},
		{
			MethodName: "DeletePerson",
			Handler:    _BaseService_DeletePerson_Handler,
		},
		{
			MethodName: "ListCohorts",
			Handler:    _BaseService_ListCohorts_Handler,
		},
		{
			MethodName: "CreateCohort",
			Handler:    _BaseService_CreateCohort_Handler,
		},
		{
			MethodName: "DeleteCohort",
			Handler:    _BaseService_DeleteCohort_Handler,
		},
		{
			MethodName: "ListFeatureFlags",
			Handler:    _BaseService_ListFeatureFlags_Handler,
		},
		{
			MethodName: "CreateFeatureFlag",
			Handler:    _BaseService_CreateFeatureFlag_Handler,
		},
		{
			MethodName: "UpdateFeatureFlag",
			Handler:    _BaseService_UpdateFeatureFlag_Handler,
		},
		{
			MethodName: "DeleteFeatureFlag",
			Handler:    _BaseService_DeleteFeatureFlag_Handler,
		},
		{
			MethodName: "EvaluateFlags",
			Handler:    _BaseService_EvaluateFlags_Handler,
		},
		{
			MethodName: "Decide",
			Handler:    _BaseService_Decide_Handler,
		},
		{
			MethodName: "CaptureEvent",
			Handler:    _BaseService_CaptureEvent_Handler,
		},
		{
			MethodName: "BatchCapture",
			Handler:    _BaseService_BatchCapture_Handler,
		},
		{
			MethodName: "Identify",
			Handler:    _BaseService_Identify_Handler,
		},
		{
			MethodName: "Alias",
			Handler:    _BaseService_Alias_Handler,
		},
		{
			MethodName: "IngestReplay",
			Handler:    _BaseService_IngestReplay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/openclick/v1/openclick.proto",
}
