// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/openclick/v1/openclick.proto

package openclick_v1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_openclick_v1_openclick_proto protoreflect.FileDescriptor

const file_proto_openclick_v1_openclick_proto_rawDesc = "" +
	"\n" +
	"\"proto/openclick/v1/openclick.proto\x12\x02v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17proto/common/ping.proto2\x8d\x01\n" +
	"\vBaseService\x12~\n" +
	"\x04Ping\x12\x0f.v1.PingRequest\x1a\x10.v1.PingResponse\"S\x92A6\n" +
	"\x04Ping\x12\x0fPing the server\x1a\x1dCheck if the server is alive.\x82\xd3\xe4\x93\x02\x14\x12\x12/openclick/v1/pingB\x82\x03\x92A\xee\x02\x12\xf0\x01\n" +
	"\x0eOpenClick APIs\x12\xd5\x01**OpenClick** is an open-source, self-hostable product analytics platform built for speed and low memory footprint. It provides event tracking, session replay, funnel analysis, feature flags, and cohort analytics.2\x06v1.0.0Z<\n" +
	"\x19\n" +
	"\x06UserID\x12\x0f\b\x02\x1a\tx-user-id \x02\n" +
	"\x1f\n" +
	"\tUserPerms\x12\x12\b\x02\x1a\fx-user-perms \x02b\x1b\n" +
	"\n" +
	"\n" +
	"\x06UserID\x12\x00\n" +
	"\r\n" +
	"\tUserPerms\x12\x00j\x1e\n" +
	"\x04Ping\x12\x16Health check endpointsZ\x0e./openclick_v1b\x06proto3"

var file_proto_openclick_v1_openclick_proto_goTypes = []any{
	(*PingRequest)(nil),  // 0: v1.PingRequest
	(*PingResponse)(nil), // 1: v1.PingResponse
}
var file_proto_openclick_v1_openclick_proto_depIdxs = []int32{
	0, // 0: v1.BaseService.Ping:input_type -> v1.PingRequest
	1, // 1: v1.BaseService.Ping:output_type -> v1.PingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_openclick_v1_openclick_proto_init() }
func file_proto_openclick_v1_openclick_proto_init() {
	if File_proto_openclick_v1_openclick_proto != nil {
		return
	}
	file_proto_common_ping_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_openclick_v1_openclick_proto_rawDesc), len(file_proto_openclick_v1_openclick_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_openclick_v1_openclick_proto_goTypes,
		DependencyIndexes: file_proto_openclick_v1_openclick_proto_depIdxs,
	}.Build()
	File_proto_openclick_v1_openclick_proto = out.File
	file_proto_openclick_v1_openclick_proto_goTypes = nil
	file_proto_openclick_v1_openclick_proto_depIdxs = nil
}
