// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: proto/openclick/v1/person.proto

package openclick_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DistinctId    string                 `protobuf:"bytes,2,opt,name=distinct_id,json=distinctId,proto3" json:"distinct_id,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,3,opt,name=properties,proto3" json:"properties,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonResponse) Reset() {
	*x = PersonResponse{}
	mi := &file_proto_openclick_v1_person_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonResponse) ProtoMessage() {}

func (x *PersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openclick_v1_person_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonResponse.ProtoReflect.Descriptor instead.
func (*PersonResponse) Descriptor() ([]byte, []int) {
	return file_proto_openclick_v1_person_proto_rawDescGZIP(), []int{0}
}

func (x *PersonResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PersonResponse) GetDistinctId() string {
	if x != nil {
		return x.DistinctId
	}
	return ""
}

func (x *PersonResponse) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *PersonResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListPersonsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Search        *string                `protobuf:"bytes,2,opt,name=search,proto3,oneof" json:"search,omitempty"`
	Limit         *int32                 `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,4,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonsRequest) Reset() {
	*x = ListPersonsRequest{}
	mi := &file_proto_openclick_v1_person_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonsRequest) ProtoMessage() {}

func (x *ListPersonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openclick_v1_person_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonsRequest.ProtoReflect.Descriptor instead.
func (*ListPersonsRequest) Descriptor() ([]byte, []int) {
	return file_proto_openclick_v1_person_proto_rawDescGZIP(), []int{1}
}

func (x *ListPersonsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListPersonsRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *ListPersonsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListPersonsRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type ListPersonsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PersonResponse      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonsResponse) Reset() {
	*x = ListPersonsResponse{}
	mi := &file_proto_openclick_v1_person_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonsResponse) ProtoMessage() {}

func (x *ListPersonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openclick_v1_person_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonsResponse.ProtoReflect.Descriptor instead.
func (*ListPersonsResponse) Descriptor() ([]byte, []int) {
	return file_proto_openclick_v1_person_proto_rawDescGZIP(), []int{2}
}

func (x *ListPersonsResponse) GetResults() []*PersonResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListPersonsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetPersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	DistinctId    string                 `protobuf:"bytes,2,opt,name=distinct_id,json=distinctId,proto3" json:"distinct_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonRequest) Reset() {
	*x = GetPersonRequest{}
	mi := &file_proto_openclick_v1_person_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonRequest) ProtoMessage() {}

func (x *GetPersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openclick_v1_person_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonRequest.ProtoReflect.Descriptor instead.
func (*GetPersonRequest) Descriptor() ([]byte, []int) {
	return file_proto_openclick_v1_person_proto_rawDescGZIP(), []int{3}
}

func (x *GetPersonRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetPersonRequest) GetDistinctId() string {
	if x != nil {
		return x.DistinctId
	}
	return ""
}

type GetPersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Person        *PersonResponse        `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	RecentEvents  []*EventResult         `protobuf:"bytes,2,rep,name=recent_events,json=recentEvents,proto3" json:"recent_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonResponse) Reset() {
	*x = GetPersonResponse{}
	mi := &file_proto_openclick_v1_person_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonResponse) ProtoMessage() {}

func (x *GetPersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openclick_v1_person_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonResponse.ProtoReflect.Descriptor instead.
func (*GetPersonResponse) Descriptor() ([]byte, []int) {
	return file_proto_openclick_v1_person_proto_rawDescGZIP(), []int{4}
}

func (x *GetPersonResponse) GetPerson() *PersonResponse {
	if x != nil {
		return x.Person
	}
	return nil
}

func (x *GetPersonResponse) GetRecentEvents() []*EventResult {
	if x != nil {
		return x.RecentEvents
	}
	return nil
}

type DeletePersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	DistinctId    string                 `protobuf:"bytes,2,opt,name=distinct_id,json=distinctId,proto3" json:"distinct_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePersonRequest) Reset() {
	*x = DeletePersonRequest{}
	mi := &file_proto_openclick_v1_person_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePersonRequest) ProtoMessage() {}

func (x *DeletePersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openclick_v1_person_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePersonRequest.ProtoReflect.Descriptor instead.
func (*DeletePersonRequest) Descriptor() ([]byte, []int) {
	return file_proto_openclick_v1_person_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePersonRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeletePersonRequest) GetDistinctId() string {
	if x != nil {
		return x.DistinctId
	}
	return ""
}

type DeletePersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePersonResponse) Reset() {
	*x = DeletePersonResponse{}
	mi := &file_proto_openclick_v1_person_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePersonResponse) ProtoMessage() {}

func (x *DeletePersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openclick_v1_person_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePersonResponse.ProtoReflect.Descriptor instead.
func (*DeletePersonResponse) Descriptor() ([]byte, []int) {
	return file_proto_openclick_v1_person_proto_rawDescGZIP(), []int{6}
}

type CohortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Filters       *structpb.Struct       `protobuf:"bytes,3,opt,name=filters,proto3" json:"filters,omitempty"`
	PersonCount   int64                  `protobuf:"varint,4,opt,name=person_count,json=personCount,proto3" json:"person_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CohortResponse) Reset() {
	*x = CohortResponse{}
	mi := &file_proto_openclick_v1_person_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CohortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CohortResponse) ProtoMessage() {}

func (x *CohortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openclick_v1_person_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CohortResponse.ProtoReflect.Descriptor instead.
func (*CohortResponse) Descriptor() ([]byte, []int) {
	return file_proto_openclick_v1_person_proto_rawDescGZIP(), []int{7}
}

func (x *CohortResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CohortResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CohortResponse) GetFilters() *structpb.Struct {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *CohortResponse) GetPersonCount() int64 {
	if x != nil {
		return x.PersonCount
	}
	return 0
}

func (x *CohortResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListCohortsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCohortsRequest) Reset() {
	*x = ListCohortsRequest{}
	mi := &file_proto_openclick_v1_person_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCohortsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCohortsRequest) ProtoMessage() {}

func (x *ListCohortsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openclick_v1_person_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCohortsRequest.ProtoReflect.Descriptor instead.
func (*ListCohortsRequest) Descriptor() ([]byte, []int) {
	return file_proto_openclick_v1_person_proto_rawDescGZIP(), []int{8}
}

func (x *ListCohortsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListCohortsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*CohortResponse      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCohortsResponse) Reset() {
	*x = ListCohortsResponse{}
	mi := &file_proto_openclick_v1_person_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCohortsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCohortsResponse) ProtoMessage() {}

func (x *ListCohortsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openclick_v1_person_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCohortsResponse.ProtoReflect.Descriptor instead.
func (*ListCohortsResponse) Descriptor() ([]byte, []int) {
	return file_proto_openclick_v1_person_proto_rawDescGZIP(), []int{9}
}

func (x *ListCohortsResponse) GetResults() []*CohortResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

type CreateCohortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Filters       *structpb.Struct       `protobuf:"bytes,3,opt,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCohortRequest) Reset() {
	*x = CreateCohortRequest{}
	mi := &file_proto_openclick_v1_person_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCohortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCohortRequest) ProtoMessage() {}

func (x *CreateCohortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openclick_v1_person_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCohortRequest.ProtoReflect.Descriptor instead.
func (*CreateCohortRequest) Descriptor() ([]byte, []int) {
	return file_proto_openclick_v1_person_proto_rawDescGZIP(), []int{10}
}

func (x *CreateCohortRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateCohortRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCohortRequest) GetFilters() *structpb.Struct {
	if x != nil {
		return x.Filters
	}
	return nil
}

type DeleteCohortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	CohortId      string                 `protobuf:"bytes,2,opt,name=cohort_id,json=cohortId,proto3" json:"cohort_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCohortRequest) Reset() {
	*x = DeleteCohortRequest{}
	mi := &file_proto_openclick_v1_person_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCohortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCohortRequest) ProtoMessage() {}

func (x *DeleteCohortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openclick_v1_person_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCohortRequest.ProtoReflect.Descriptor instead.
func (*DeleteCohortRequest) Descriptor() ([]byte, []int) {
	return file_proto_openclick_v1_person_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteCohortRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeleteCohortRequest) GetCohortId() string {
	if x != nil {
		return x.CohortId
	}
	return ""
}

type DeleteCohortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCohortResponse) Reset() {
	*x = DeleteCohortResponse{}
	mi := &file_proto_openclick_v1_person_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCohortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCohortResponse) ProtoMessage() {}

func (x *DeleteCohortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openclick_v1_person_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCohortResponse.ProtoReflect.Descriptor instead.
func (*DeleteCohortResponse) Descriptor() ([]byte, []int) {
	return file_proto_openclick_v1_person_proto_rawDescGZIP(), []int{12}
}

type DeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,3,opt,name=properties,proto3" json:"properties,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceResponse) Reset() {
	*x = DeviceResponse{}
	mi := &file_proto_openclick_v1_person_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceResponse) ProtoMessage() {}

func (x *DeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openclick_v1_person_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceResponse.ProtoReflect.Descriptor instead.
func (*DeviceResponse) Descriptor() ([]byte, []int) {
	return file_proto_openclick_v1_person_proto_rawDescGZIP(), []int{13}
}

func (x *DeviceResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeviceResponse) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *DeviceResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DeviceResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Limit         *int32                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	DeviceId      *string                `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3,oneof" json:"device_id,omitempty"` // exact match search
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_proto_openclick_v1_person_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openclick_v1_person_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_openclick_v1_person_proto_rawDescGZIP(), []int{14}
}

func (x *ListDevicesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListDevicesRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListDevicesRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ListDevicesRequest) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*DeviceResponse      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_proto_openclick_v1_person_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openclick_v1_person_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_openclick_v1_person_proto_rawDescGZIP(), []int{15}
}

func (x *ListDevicesResponse) GetResults() []*DeviceResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListDevicesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceRequest) Reset() {
	*x = GetDeviceRequest{}
	mi := &file_proto_openclick_v1_person_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceRequest) ProtoMessage() {}

func (x *GetDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openclick_v1_person_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceRequest) Descriptor() ([]byte, []int) {
	return file_proto_openclick_v1_person_proto_rawDescGZIP(), []int{16}
}

func (x *GetDeviceRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type GetDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *DeviceResponse        `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceResponse) Reset() {
	*x = GetDeviceResponse{}
	mi := &file_proto_openclick_v1_person_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceResponse) ProtoMessage() {}

func (x *GetDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openclick_v1_person_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceResponse) Descriptor() ([]byte, []int) {
	return file_proto_openclick_v1_person_proto_rawDescGZIP(), []int{17}
}

func (x *GetDeviceResponse) GetDevice() *DeviceResponse {
	if x != nil {
		return x.Device
	}
	return nil
}

type DeviceStatItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStatItem) Reset() {
	*x = DeviceStatItem{}
	mi := &file_proto_openclick_v1_person_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatItem) ProtoMessage() {}

func (x *DeviceStatItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openclick_v1_person_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatItem.ProtoReflect.Descriptor instead.
func (*DeviceStatItem) Descriptor() ([]byte, []int) {
	return file_proto_openclick_v1_person_proto_rawDescGZIP(), []int{18}
}

func (x *DeviceStatItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DeviceStatItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetDeviceStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceStatsRequest) Reset() {
	*x = GetDeviceStatsRequest{}
	mi := &file_proto_openclick_v1_person_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceStatsRequest) ProtoMessage() {}

func (x *GetDeviceStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openclick_v1_person_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceStatsRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_openclick_v1_person_proto_rawDescGZIP(), []int{19}
}

func (x *GetDeviceStatsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type GetDeviceStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Browsers      []*DeviceStatItem      `protobuf:"bytes,1,rep,name=browsers,proto3" json:"browsers,omitempty"`
	OsList        []*DeviceStatItem      `protobuf:"bytes,2,rep,name=os_list,json=osList,proto3" json:"os_list,omitempty"`
	DeviceTypes   []*DeviceStatItem      `protobuf:"bytes,3,rep,name=device_types,json=deviceTypes,proto3" json:"device_types,omitempty"`
	Libs          []*DeviceStatItem      `protobuf:"bytes,4,rep,name=libs,proto3" json:"libs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceStatsResponse) Reset() {
	*x = GetDeviceStatsResponse{}
	mi := &file_proto_openclick_v1_person_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceStatsResponse) ProtoMessage() {}

func (x *GetDeviceStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openclick_v1_person_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceStatsResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_openclick_v1_person_proto_rawDescGZIP(), []int{20}
}

func (x *GetDeviceStatsResponse) GetBrowsers() []*DeviceStatItem {
	if x != nil {
		return x.Browsers
	}
	return nil
}

func (x *GetDeviceStatsResponse) GetOsList() []*DeviceStatItem {
	if x != nil {
		return x.OsList
	}
	return nil
}

func (x *GetDeviceStatsResponse) GetDeviceTypes() []*DeviceStatItem {
	if x != nil {
		return x.DeviceTypes
	}
	return nil
}

func (x *GetDeviceStatsResponse) GetLibs() []*DeviceStatItem {
	if x != nil {
		return x.Libs
	}
	return nil
}

var File_proto_openclick_v1_person_proto protoreflect.FileDescriptor

const file_proto_openclick_v1_person_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/openclick/v1/person.proto\x12\x02v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\"proto/openclick/v1/analytics.proto\"\xb5\x01\n" +
	"\x0ePersonResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdistinct_id\x18\x02 \x01(\tR\n" +
	"distinctId\x127\n" +
	"\n" +
	"properties\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa8\x01\n" +
	"\x12ListPersonsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1b\n" +
	"\x06search\x18\x02 \x01(\tH\x00R\x06search\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x05H\x01R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x04 \x01(\x05H\x02R\x06offset\x88\x01\x01B\t\n" +
	"\a_searchB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"Y\n" +
	"\x13ListPersonsResponse\x12,\n" +
	"\aresults\x18\x01 \x03(\v2\x12.v1.PersonResponseR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"R\n" +
	"\x10GetPersonRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vdistinct_id\x18\x02 \x01(\tR\n" +
	"distinctId\"u\n" +
	"\x11GetPersonResponse\x12*\n" +
	"\x06person\x18\x01 \x01(\v2\x12.v1.PersonResponseR\x06person\x124\n" +
	"\rrecent_events\x18\x02 \x03(\v2\x0f.v1.EventResultR\frecentEvents\"U\n" +
	"\x13DeletePersonRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vdistinct_id\x18\x02 \x01(\tR\n" +
	"distinctId\"\x16\n" +
	"\x14DeletePersonResponse\"\xc5\x01\n" +
	"\x0eCohortResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x121\n" +
	"\afilters\x18\x03 \x01(\v2\x17.google.protobuf.StructR\afilters\x12!\n" +
	"\fperson_count\x18\x04 \x01(\x03R\vpersonCount\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"3\n" +
	"\x12ListCohortsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"C\n" +
	"\x13ListCohortsResponse\x12,\n" +
	"\aresults\x18\x01 \x03(\v2\x12.v1.CohortResponseR\aresults\"{\n" +
	"\x13CreateCohortRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x121\n" +
	"\afilters\x18\x03 \x01(\v2\x17.google.protobuf.StructR\afilters\"Q\n" +
	"\x13DeleteCohortRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1b\n" +
	"\tcohort_id\x18\x02 \x01(\tR\bcohortId\"\x16\n" +
	"\x14DeleteCohortResponse\"\xee\x01\n" +
	"\x0eDeviceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x127\n" +
	"\n" +
	"properties\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb0\x01\n" +
	"\x12ListDevicesRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x03 \x01(\x05H\x01R\x06offset\x88\x01\x01\x12 \n" +
	"\tdevice_id\x18\x04 \x01(\tH\x02R\bdeviceId\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\f\n" +
	"\n" +
	"_device_id\"Y\n" +
	"\x13ListDevicesResponse\x12,\n" +
	"\aresults\x18\x01 \x03(\v2\x12.v1.DeviceResponseR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"N\n" +
	"\x10GetDeviceRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"?\n" +
	"\x11GetDeviceResponse\x12*\n" +
	"\x06device\x18\x01 \x01(\v2\x12.v1.DeviceResponseR\x06device\"<\n" +
	"\x0eDeviceStatItem\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"6\n" +
	"\x15GetDeviceStatsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"\xd4\x01\n" +
	"\x16GetDeviceStatsResponse\x12.\n" +
	"\bbrowsers\x18\x01 \x03(\v2\x12.v1.DeviceStatItemR\bbrowsers\x12+\n" +
	"\aos_list\x18\x02 \x03(\v2\x12.v1.DeviceStatItemR\x06osList\x125\n" +
	"\fdevice_types\x18\x03 \x03(\v2\x12.v1.DeviceStatItemR\vdeviceTypes\x12&\n" +
	"\x04libs\x18\x04 \x03(\v2\x12.v1.DeviceStatItemR\x04libsB\x10Z\x0e./openclick_v1b\x06proto3"

var (
	file_proto_openclick_v1_person_proto_rawDescOnce sync.Once
	file_proto_openclick_v1_person_proto_rawDescData []byte
)

func file_proto_openclick_v1_person_proto_rawDescGZIP() []byte {
	file_proto_openclick_v1_person_proto_rawDescOnce.Do(func() {
		file_proto_openclick_v1_person_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_openclick_v1_person_proto_rawDesc), len(file_proto_openclick_v1_person_proto_rawDesc)))
	})
	return file_proto_openclick_v1_person_proto_rawDescData
}

var file_proto_openclick_v1_person_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_openclick_v1_person_proto_goTypes = []any{
	(*PersonResponse)(nil),         // 0: v1.PersonResponse
	(*ListPersonsRequest)(nil),     // 1: v1.ListPersonsRequest
	(*ListPersonsResponse)(nil),    // 2: v1.ListPersonsResponse
	(*GetPersonRequest)(nil),       // 3: v1.GetPersonRequest
	(*GetPersonResponse)(nil),      // 4: v1.GetPersonResponse
	(*DeletePersonRequest)(nil),    // 5: v1.DeletePersonRequest
	(*DeletePersonResponse)(nil),   // 6: v1.DeletePersonResponse
	(*CohortResponse)(nil),         // 7: v1.CohortResponse
	(*ListCohortsRequest)(nil),     // 8: v1.ListCohortsRequest
	(*ListCohortsResponse)(nil),    // 9: v1.ListCohortsResponse
	(*CreateCohortRequest)(nil),    // 10: v1.CreateCohortRequest
	(*DeleteCohortRequest)(nil),    // 11: v1.DeleteCohortRequest
	(*DeleteCohortResponse)(nil),   // 12: v1.DeleteCohortResponse
	(*DeviceResponse)(nil),         // 13: v1.DeviceResponse
	(*ListDevicesRequest)(nil),     // 14: v1.ListDevicesRequest
	(*ListDevicesResponse)(nil),    // 15: v1.ListDevicesResponse
	(*GetDeviceRequest)(nil),       // 16: v1.GetDeviceRequest
	(*GetDeviceResponse)(nil),      // 17: v1.GetDeviceResponse
	(*DeviceStatItem)(nil),         // 18: v1.DeviceStatItem
	(*GetDeviceStatsRequest)(nil),  // 19: v1.GetDeviceStatsRequest
	(*GetDeviceStatsResponse)(nil), // 20: v1.GetDeviceStatsResponse
	(*structpb.Struct)(nil),        // 21: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),  // 22: google.protobuf.Timestamp
	(*EventResult)(nil),            // 23: v1.EventResult
}
var file_proto_openclick_v1_person_proto_depIdxs = []int32{
	21, // 0: v1.PersonResponse.properties:type_name -> google.protobuf.Struct
	22, // 1: v1.PersonResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: v1.ListPersonsResponse.results:type_name -> v1.PersonResponse
	0,  // 3: v1.GetPersonResponse.person:type_name -> v1.PersonResponse
	23, // 4: v1.GetPersonResponse.recent_events:type_name -> v1.EventResult
	21, // 5: v1.CohortResponse.filters:type_name -> google.protobuf.Struct
	22, // 6: v1.CohortResponse.created_at:type_name -> google.protobuf.Timestamp
	7,  // 7: v1.ListCohortsResponse.results:type_name -> v1.CohortResponse
	21, // 8: v1.CreateCohortRequest.filters:type_name -> google.protobuf.Struct
	21, // 9: v1.DeviceResponse.properties:type_name -> google.protobuf.Struct
	22, // 10: v1.DeviceResponse.created_at:type_name -> google.protobuf.Timestamp
	22, // 11: v1.DeviceResponse.updated_at:type_name -> google.protobuf.Timestamp
	13, // 12: v1.ListDevicesResponse.results:type_name -> v1.DeviceResponse
	13, // 13: v1.GetDeviceResponse.device:type_name -> v1.DeviceResponse
	18, // 14: v1.GetDeviceStatsResponse.browsers:type_name -> v1.DeviceStatItem
	18, // 15: v1.GetDeviceStatsResponse.os_list:type_name -> v1.DeviceStatItem
	18, // 16: v1.GetDeviceStatsResponse.device_types:type_name -> v1.DeviceStatItem
	18, // 17: v1.GetDeviceStatsResponse.libs:type_name -> v1.DeviceStatItem
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_openclick_v1_person_proto_init() }
func file_proto_openclick_v1_person_proto_init() {
	if File_proto_openclick_v1_person_proto != nil {
		return
	}
	file_proto_openclick_v1_analytics_proto_init()
	file_proto_openclick_v1_person_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_openclick_v1_person_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_openclick_v1_person_proto_rawDesc), len(file_proto_openclick_v1_person_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_openclick_v1_person_proto_goTypes,
		DependencyIndexes: file_proto_openclick_v1_person_proto_depIdxs,
		MessageInfos:      file_proto_openclick_v1_person_proto_msgTypes,
	}.Build()
	File_proto_openclick_v1_person_proto = out.File
	file_proto_openclick_v1_person_proto_goTypes = nil
	file_proto_openclick_v1_person_proto_depIdxs = nil
}
