// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/openclick/v1/person.proto

package openclick_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PersonResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PersonResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PersonResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PersonResponseMultiError,
// or nil if none found.
func (m *PersonResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PersonResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for DistinctId

	if all {
		switch v := interface{}(m.GetProperties()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PersonResponseValidationError{
					field:  "Properties",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PersonResponseValidationError{
					field:  "Properties",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProperties()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PersonResponseValidationError{
				field:  "Properties",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, PersonResponseValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, PersonResponseValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PersonResponseValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return PersonResponseMultiError(errors)
	}

	return nil
}

// PersonResponseMultiError is an error wrapping multiple validation errors
// returned by PersonResponse.ValidateAll() if the designated constraints
// aren't met.
type PersonResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PersonResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PersonResponseMultiError) AllErrors() []error { return m }

// PersonResponseValidationError is the validation error returned by
// PersonResponse.Validate if the designated constraints aren't met.
type PersonResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PersonResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PersonResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PersonResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PersonResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PersonResponseValidationError) ErrorName() string { return "PersonResponseValidationError" }

// Error satisfies the builtin error interface
func (e PersonResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPersonResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PersonResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PersonResponseValidationError{}

// Validate checks the field values on ListPersonsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListPersonsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPersonsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPersonsRequestMultiError, or nil if none found.
func (m *ListPersonsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPersonsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectId

	if m.Search != nil {
		// no validation rules for Search
	}

	if m.Limit != nil {
		// no validation rules for Limit
	}

	if m.Offset != nil {
		// no validation rules for Offset
	}

	if len(errors) > 0 {
		return ListPersonsRequestMultiError(errors)
	}

	return nil
}

// ListPersonsRequestMultiError is an error wrapping multiple validation errors
// returned by ListPersonsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListPersonsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPersonsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPersonsRequestMultiError) AllErrors() []error { return m }

// ListPersonsRequestValidationError is the validation error returned by
// ListPersonsRequest.Validate if the designated constraints aren't met.
type ListPersonsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPersonsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPersonsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPersonsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPersonsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPersonsRequestValidationError) ErrorName() string {
	return "ListPersonsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListPersonsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPersonsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPersonsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPersonsRequestValidationError{}

// Validate checks the field values on ListPersonsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListPersonsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListPersonsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListPersonsResponseMultiError, or nil if none found.
func (m *ListPersonsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListPersonsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetResults() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListPersonsResponseValidationError{
						field:  fmt.Sprintf("Results[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListPersonsResponseValidationError{
						field:  fmt.Sprintf("Results[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListPersonsResponseValidationError{
					field:  fmt.Sprintf("Results[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return ListPersonsResponseMultiError(errors)
	}

	return nil
}

// ListPersonsResponseMultiError is an error wrapping multiple validation
// errors returned by ListPersonsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListPersonsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListPersonsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListPersonsResponseMultiError) AllErrors() []error { return m }

// ListPersonsResponseValidationError is the validation error returned by
// ListPersonsResponse.Validate if the designated constraints aren't met.
type ListPersonsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListPersonsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListPersonsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListPersonsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListPersonsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListPersonsResponseValidationError) ErrorName() string {
	return "ListPersonsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListPersonsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListPersonsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListPersonsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListPersonsResponseValidationError{}

// Validate checks the field values on GetPersonRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetPersonRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPersonRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetPersonRequestMultiError, or nil if none found.
func (m *GetPersonRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPersonRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectId

	// no validation rules for DistinctId

	if len(errors) > 0 {
		return GetPersonRequestMultiError(errors)
	}

	return nil
}

// GetPersonRequestMultiError is an error wrapping multiple validation errors
// returned by GetPersonRequest.ValidateAll() if the designated constraints
// aren't met.
type GetPersonRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPersonRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPersonRequestMultiError) AllErrors() []error { return m }

// GetPersonRequestValidationError is the validation error returned by
// GetPersonRequest.Validate if the designated constraints aren't met.
type GetPersonRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPersonRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPersonRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPersonRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPersonRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPersonRequestValidationError) ErrorName() string { return "GetPersonRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetPersonRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPersonRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPersonRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPersonRequestValidationError{}

// Validate checks the field values on GetPersonResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetPersonResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPersonResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetPersonResponseMultiError, or nil if none found.
func (m *GetPersonResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPersonResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPerson()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetPersonResponseValidationError{
					field:  "Person",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetPersonResponseValidationError{
					field:  "Person",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPerson()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetPersonResponseValidationError{
				field:  "Person",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetRecentEvents() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetPersonResponseValidationError{
						field:  fmt.Sprintf("RecentEvents[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetPersonResponseValidationError{
						field:  fmt.Sprintf("RecentEvents[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetPersonResponseValidationError{
					field:  fmt.Sprintf("RecentEvents[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetPersonResponseMultiError(errors)
	}

	return nil
}

// GetPersonResponseMultiError is an error wrapping multiple validation errors
// returned by GetPersonResponse.ValidateAll() if the designated constraints
// aren't met.
type GetPersonResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPersonResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPersonResponseMultiError) AllErrors() []error { return m }

// GetPersonResponseValidationError is the validation error returned by
// GetPersonResponse.Validate if the designated constraints aren't met.
type GetPersonResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPersonResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPersonResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPersonResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPersonResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPersonResponseValidationError) ErrorName() string {
	return "GetPersonResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetPersonResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPersonResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPersonResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPersonResponseValidationError{}

// Validate checks the field values on DeletePersonRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeletePersonRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeletePersonRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeletePersonRequestMultiError, or nil if none found.
func (m *DeletePersonRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeletePersonRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectId

	// no validation rules for DistinctId

	if len(errors) > 0 {
		return DeletePersonRequestMultiError(errors)
	}

	return nil
}

// DeletePersonRequestMultiError is an error wrapping multiple validation
// errors returned by DeletePersonRequest.ValidateAll() if the designated
// constraints aren't met.
type DeletePersonRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeletePersonRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeletePersonRequestMultiError) AllErrors() []error { return m }

// DeletePersonRequestValidationError is the validation error returned by
// DeletePersonRequest.Validate if the designated constraints aren't met.
type DeletePersonRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeletePersonRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeletePersonRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeletePersonRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeletePersonRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeletePersonRequestValidationError) ErrorName() string {
	return "DeletePersonRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeletePersonRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeletePersonRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeletePersonRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeletePersonRequestValidationError{}

// Validate checks the field values on DeletePersonResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeletePersonResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeletePersonResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeletePersonResponseMultiError, or nil if none found.
func (m *DeletePersonResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeletePersonResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeletePersonResponseMultiError(errors)
	}

	return nil
}

// DeletePersonResponseMultiError is an error wrapping multiple validation
// errors returned by DeletePersonResponse.ValidateAll() if the designated
// constraints aren't met.
type DeletePersonResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeletePersonResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeletePersonResponseMultiError) AllErrors() []error { return m }

// DeletePersonResponseValidationError is the validation error returned by
// DeletePersonResponse.Validate if the designated constraints aren't met.
type DeletePersonResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeletePersonResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeletePersonResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeletePersonResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeletePersonResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeletePersonResponseValidationError) ErrorName() string {
	return "DeletePersonResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeletePersonResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeletePersonResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeletePersonResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeletePersonResponseValidationError{}

// Validate checks the field values on CohortResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CohortResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CohortResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CohortResponseMultiError,
// or nil if none found.
func (m *CohortResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CohortResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	if all {
		switch v := interface{}(m.GetFilters()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CohortResponseValidationError{
					field:  "Filters",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CohortResponseValidationError{
					field:  "Filters",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFilters()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CohortResponseValidationError{
				field:  "Filters",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for PersonCount

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CohortResponseValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CohortResponseValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CohortResponseValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CohortResponseMultiError(errors)
	}

	return nil
}

// CohortResponseMultiError is an error wrapping multiple validation errors
// returned by CohortResponse.ValidateAll() if the designated constraints
// aren't met.
type CohortResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CohortResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CohortResponseMultiError) AllErrors() []error { return m }

// CohortResponseValidationError is the validation error returned by
// CohortResponse.Validate if the designated constraints aren't met.
type CohortResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CohortResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CohortResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CohortResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CohortResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CohortResponseValidationError) ErrorName() string { return "CohortResponseValidationError" }

// Error satisfies the builtin error interface
func (e CohortResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCohortResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CohortResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CohortResponseValidationError{}

// Validate checks the field values on ListCohortsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListCohortsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListCohortsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListCohortsRequestMultiError, or nil if none found.
func (m *ListCohortsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListCohortsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectId

	if len(errors) > 0 {
		return ListCohortsRequestMultiError(errors)
	}

	return nil
}

// ListCohortsRequestMultiError is an error wrapping multiple validation errors
// returned by ListCohortsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListCohortsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListCohortsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListCohortsRequestMultiError) AllErrors() []error { return m }

// ListCohortsRequestValidationError is the validation error returned by
// ListCohortsRequest.Validate if the designated constraints aren't met.
type ListCohortsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListCohortsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListCohortsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListCohortsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListCohortsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListCohortsRequestValidationError) ErrorName() string {
	return "ListCohortsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListCohortsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListCohortsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListCohortsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListCohortsRequestValidationError{}

// Validate checks the field values on ListCohortsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListCohortsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListCohortsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListCohortsResponseMultiError, or nil if none found.
func (m *ListCohortsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListCohortsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetResults() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListCohortsResponseValidationError{
						field:  fmt.Sprintf("Results[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListCohortsResponseValidationError{
						field:  fmt.Sprintf("Results[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListCohortsResponseValidationError{
					field:  fmt.Sprintf("Results[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListCohortsResponseMultiError(errors)
	}

	return nil
}

// ListCohortsResponseMultiError is an error wrapping multiple validation
// errors returned by ListCohortsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListCohortsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListCohortsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListCohortsResponseMultiError) AllErrors() []error { return m }

// ListCohortsResponseValidationError is the validation error returned by
// ListCohortsResponse.Validate if the designated constraints aren't met.
type ListCohortsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListCohortsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListCohortsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListCohortsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListCohortsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListCohortsResponseValidationError) ErrorName() string {
	return "ListCohortsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListCohortsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListCohortsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListCohortsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListCohortsResponseValidationError{}

// Validate checks the field values on CreateCohortRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateCohortRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateCohortRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateCohortRequestMultiError, or nil if none found.
func (m *CreateCohortRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateCohortRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectId

	// no validation rules for Name

	if all {
		switch v := interface{}(m.GetFilters()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateCohortRequestValidationError{
					field:  "Filters",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateCohortRequestValidationError{
					field:  "Filters",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFilters()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateCohortRequestValidationError{
				field:  "Filters",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateCohortRequestMultiError(errors)
	}

	return nil
}

// CreateCohortRequestMultiError is an error wrapping multiple validation
// errors returned by CreateCohortRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateCohortRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateCohortRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateCohortRequestMultiError) AllErrors() []error { return m }

// CreateCohortRequestValidationError is the validation error returned by
// CreateCohortRequest.Validate if the designated constraints aren't met.
type CreateCohortRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateCohortRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateCohortRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateCohortRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateCohortRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateCohortRequestValidationError) ErrorName() string {
	return "CreateCohortRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateCohortRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateCohortRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateCohortRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateCohortRequestValidationError{}

// Validate checks the field values on DeleteCohortRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteCohortRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteCohortRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteCohortRequestMultiError, or nil if none found.
func (m *DeleteCohortRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteCohortRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectId

	// no validation rules for CohortId

	if len(errors) > 0 {
		return DeleteCohortRequestMultiError(errors)
	}

	return nil
}

// DeleteCohortRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteCohortRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteCohortRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteCohortRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteCohortRequestMultiError) AllErrors() []error { return m }

// DeleteCohortRequestValidationError is the validation error returned by
// DeleteCohortRequest.Validate if the designated constraints aren't met.
type DeleteCohortRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteCohortRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteCohortRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteCohortRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteCohortRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteCohortRequestValidationError) ErrorName() string {
	return "DeleteCohortRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteCohortRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteCohortRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteCohortRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteCohortRequestValidationError{}

// Validate checks the field values on DeleteCohortResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteCohortResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteCohortResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteCohortResponseMultiError, or nil if none found.
func (m *DeleteCohortResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteCohortResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteCohortResponseMultiError(errors)
	}

	return nil
}

// DeleteCohortResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteCohortResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteCohortResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteCohortResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteCohortResponseMultiError) AllErrors() []error { return m }

// DeleteCohortResponseValidationError is the validation error returned by
// DeleteCohortResponse.Validate if the designated constraints aren't met.
type DeleteCohortResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteCohortResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteCohortResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteCohortResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteCohortResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteCohortResponseValidationError) ErrorName() string {
	return "DeleteCohortResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteCohortResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteCohortResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteCohortResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteCohortResponseValidationError{}

// Validate checks the field values on DeviceResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DeviceResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeviceResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DeviceResponseMultiError,
// or nil if none found.
func (m *DeviceResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeviceResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ProjectId

	if all {
		switch v := interface{}(m.GetProperties()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DeviceResponseValidationError{
					field:  "Properties",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DeviceResponseValidationError{
					field:  "Properties",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProperties()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DeviceResponseValidationError{
				field:  "Properties",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DeviceResponseValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DeviceResponseValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DeviceResponseValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DeviceResponseValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DeviceResponseValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DeviceResponseValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DeviceResponseMultiError(errors)
	}

	return nil
}

// DeviceResponseMultiError is an error wrapping multiple validation errors
// returned by DeviceResponse.ValidateAll() if the designated constraints
// aren't met.
type DeviceResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeviceResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeviceResponseMultiError) AllErrors() []error { return m }

// DeviceResponseValidationError is the validation error returned by
// DeviceResponse.Validate if the designated constraints aren't met.
type DeviceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeviceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeviceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeviceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeviceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeviceResponseValidationError) ErrorName() string { return "DeviceResponseValidationError" }

// Error satisfies the builtin error interface
func (e DeviceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeviceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeviceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeviceResponseValidationError{}

// Validate checks the field values on ListDevicesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListDevicesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListDevicesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListDevicesRequestMultiError, or nil if none found.
func (m *ListDevicesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListDevicesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectId

	if m.Limit != nil {
		// no validation rules for Limit
	}

	if m.Offset != nil {
		// no validation rules for Offset
	}

	if m.DeviceId != nil {
		// no validation rules for DeviceId
	}

	if len(errors) > 0 {
		return ListDevicesRequestMultiError(errors)
	}

	return nil
}

// ListDevicesRequestMultiError is an error wrapping multiple validation errors
// returned by ListDevicesRequest.ValidateAll() if the designated constraints
// aren't met.
type ListDevicesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListDevicesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListDevicesRequestMultiError) AllErrors() []error { return m }

// ListDevicesRequestValidationError is the validation error returned by
// ListDevicesRequest.Validate if the designated constraints aren't met.
type ListDevicesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListDevicesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListDevicesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListDevicesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListDevicesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListDevicesRequestValidationError) ErrorName() string {
	return "ListDevicesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListDevicesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListDevicesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListDevicesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListDevicesRequestValidationError{}

// Validate checks the field values on ListDevicesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListDevicesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListDevicesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListDevicesResponseMultiError, or nil if none found.
func (m *ListDevicesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListDevicesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetResults() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListDevicesResponseValidationError{
						field:  fmt.Sprintf("Results[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListDevicesResponseValidationError{
						field:  fmt.Sprintf("Results[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListDevicesResponseValidationError{
					field:  fmt.Sprintf("Results[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return ListDevicesResponseMultiError(errors)
	}

	return nil
}

// ListDevicesResponseMultiError is an error wrapping multiple validation
// errors returned by ListDevicesResponse.ValidateAll() if the designated
// constraints aren't met.
type ListDevicesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListDevicesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListDevicesResponseMultiError) AllErrors() []error { return m }

// ListDevicesResponseValidationError is the validation error returned by
// ListDevicesResponse.Validate if the designated constraints aren't met.
type ListDevicesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListDevicesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListDevicesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListDevicesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListDevicesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListDevicesResponseValidationError) ErrorName() string {
	return "ListDevicesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListDevicesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListDevicesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListDevicesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListDevicesResponseValidationError{}

// Validate checks the field values on GetDeviceRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetDeviceRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDeviceRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDeviceRequestMultiError, or nil if none found.
func (m *GetDeviceRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDeviceRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectId

	// no validation rules for DeviceId

	if len(errors) > 0 {
		return GetDeviceRequestMultiError(errors)
	}

	return nil
}

// GetDeviceRequestMultiError is an error wrapping multiple validation errors
// returned by GetDeviceRequest.ValidateAll() if the designated constraints
// aren't met.
type GetDeviceRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDeviceRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDeviceRequestMultiError) AllErrors() []error { return m }

// GetDeviceRequestValidationError is the validation error returned by
// GetDeviceRequest.Validate if the designated constraints aren't met.
type GetDeviceRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDeviceRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDeviceRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDeviceRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDeviceRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDeviceRequestValidationError) ErrorName() string { return "GetDeviceRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetDeviceRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDeviceRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDeviceRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDeviceRequestValidationError{}

// Validate checks the field values on GetDeviceResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetDeviceResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDeviceResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDeviceResponseMultiError, or nil if none found.
func (m *GetDeviceResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDeviceResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDevice()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetDeviceResponseValidationError{
					field:  "Device",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetDeviceResponseValidationError{
					field:  "Device",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDevice()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetDeviceResponseValidationError{
				field:  "Device",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetDeviceResponseMultiError(errors)
	}

	return nil
}

// GetDeviceResponseMultiError is an error wrapping multiple validation errors
// returned by GetDeviceResponse.ValidateAll() if the designated constraints
// aren't met.
type GetDeviceResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDeviceResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDeviceResponseMultiError) AllErrors() []error { return m }

// GetDeviceResponseValidationError is the validation error returned by
// GetDeviceResponse.Validate if the designated constraints aren't met.
type GetDeviceResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDeviceResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDeviceResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDeviceResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDeviceResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDeviceResponseValidationError) ErrorName() string {
	return "GetDeviceResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetDeviceResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDeviceResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDeviceResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDeviceResponseValidationError{}

// Validate checks the field values on DeviceStatItem with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DeviceStatItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeviceStatItem with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DeviceStatItemMultiError,
// or nil if none found.
func (m *DeviceStatItem) ValidateAll() error {
	return m.validate(true)
}

func (m *DeviceStatItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Value

	// no validation rules for Count

	if len(errors) > 0 {
		return DeviceStatItemMultiError(errors)
	}

	return nil
}

// DeviceStatItemMultiError is an error wrapping multiple validation errors
// returned by DeviceStatItem.ValidateAll() if the designated constraints
// aren't met.
type DeviceStatItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeviceStatItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeviceStatItemMultiError) AllErrors() []error { return m }

// DeviceStatItemValidationError is the validation error returned by
// DeviceStatItem.Validate if the designated constraints aren't met.
type DeviceStatItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeviceStatItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeviceStatItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeviceStatItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeviceStatItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeviceStatItemValidationError) ErrorName() string { return "DeviceStatItemValidationError" }

// Error satisfies the builtin error interface
func (e DeviceStatItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeviceStatItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeviceStatItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeviceStatItemValidationError{}

// Validate checks the field values on GetDeviceStatsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetDeviceStatsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDeviceStatsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDeviceStatsRequestMultiError, or nil if none found.
func (m *GetDeviceStatsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDeviceStatsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProjectId

	if len(errors) > 0 {
		return GetDeviceStatsRequestMultiError(errors)
	}

	return nil
}

// GetDeviceStatsRequestMultiError is an error wrapping multiple validation
// errors returned by GetDeviceStatsRequest.ValidateAll() if the designated
// constraints aren't met.
type GetDeviceStatsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDeviceStatsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDeviceStatsRequestMultiError) AllErrors() []error { return m }

// GetDeviceStatsRequestValidationError is the validation error returned by
// GetDeviceStatsRequest.Validate if the designated constraints aren't met.
type GetDeviceStatsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDeviceStatsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDeviceStatsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDeviceStatsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDeviceStatsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDeviceStatsRequestValidationError) ErrorName() string {
	return "GetDeviceStatsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetDeviceStatsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDeviceStatsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDeviceStatsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDeviceStatsRequestValidationError{}

// Validate checks the field values on GetDeviceStatsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetDeviceStatsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDeviceStatsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDeviceStatsResponseMultiError, or nil if none found.
func (m *GetDeviceStatsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDeviceStatsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetBrowsers() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetDeviceStatsResponseValidationError{
						field:  fmt.Sprintf("Browsers[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetDeviceStatsResponseValidationError{
						field:  fmt.Sprintf("Browsers[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetDeviceStatsResponseValidationError{
					field:  fmt.Sprintf("Browsers[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetOsList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetDeviceStatsResponseValidationError{
						field:  fmt.Sprintf("OsList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetDeviceStatsResponseValidationError{
						field:  fmt.Sprintf("OsList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetDeviceStatsResponseValidationError{
					field:  fmt.Sprintf("OsList[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetDeviceTypes() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetDeviceStatsResponseValidationError{
						field:  fmt.Sprintf("DeviceTypes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetDeviceStatsResponseValidationError{
						field:  fmt.Sprintf("DeviceTypes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetDeviceStatsResponseValidationError{
					field:  fmt.Sprintf("DeviceTypes[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetLibs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetDeviceStatsResponseValidationError{
						field:  fmt.Sprintf("Libs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetDeviceStatsResponseValidationError{
						field:  fmt.Sprintf("Libs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetDeviceStatsResponseValidationError{
					field:  fmt.Sprintf("Libs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetDeviceStatsResponseMultiError(errors)
	}

	return nil
}

// GetDeviceStatsResponseMultiError is an error wrapping multiple validation
// errors returned by GetDeviceStatsResponse.ValidateAll() if the designated
// constraints aren't met.
type GetDeviceStatsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDeviceStatsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDeviceStatsResponseMultiError) AllErrors() []error { return m }

// GetDeviceStatsResponseValidationError is the validation error returned by
// GetDeviceStatsResponse.Validate if the designated constraints aren't met.
type GetDeviceStatsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDeviceStatsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDeviceStatsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDeviceStatsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDeviceStatsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDeviceStatsResponseValidationError) ErrorName() string {
	return "GetDeviceStatsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetDeviceStatsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDeviceStatsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDeviceStatsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDeviceStatsResponseValidationError{}
