// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: proto/openclick/v1/feature_flag.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Struct } from "../../../google/protobuf/struct";
import { Timestamp } from "../../../google/protobuf/timestamp";

export const protobufPackage = "v1";

export interface FeatureFlagResponse {
  id: string;
  key: string;
  name: string;
  active: boolean;
  rolloutPct: number;
  filters: { [key: string]: any } | undefined;
  createdAt: Date | undefined;
}

export interface ListFeatureFlagsRequest {
  projectId: string;
}

export interface ListFeatureFlagsResponse {
  results: FeatureFlagResponse[];
}

export interface CreateFeatureFlagRequest {
  projectId: string;
  key: string;
  name: string;
  active: boolean;
  rolloutPct: number;
  filters: { [key: string]: any } | undefined;
}

export interface UpdateFeatureFlagRequest {
  projectId: string;
  flagId: string;
  name?: string | undefined;
  active?: boolean | undefined;
  rolloutPct?: number | undefined;
  filters: { [key: string]: any } | undefined;
}

export interface DeleteFeatureFlagRequest {
  projectId: string;
  flagId: string;
}

export interface DeleteFeatureFlagResponse {
}

export interface EvaluateFlagsRequest {
  projectId: string;
  distinctId: string;
  personProperties: { [key: string]: any } | undefined;
  groups: { [key: string]: any } | undefined;
}

export interface EvaluateFlagsResponse {
  featureFlags: { [key: string]: boolean };
}

export interface EvaluateFlagsResponse_FeatureFlagsEntry {
  key: string;
  value: boolean;
}

export interface DecideRequest {
  apiKey?: string | undefined;
  distinctId: string;
}

export interface DecideResponse {
  featureFlags: { [key: string]: boolean };
}

export interface DecideResponse_FeatureFlagsEntry {
  key: string;
  value: boolean;
}

function createBaseFeatureFlagResponse(): FeatureFlagResponse {
  return { id: "", key: "", name: "", active: false, rolloutPct: 0, filters: undefined, createdAt: undefined };
}

export const FeatureFlagResponse: MessageFns<FeatureFlagResponse> = {
  encode(message: FeatureFlagResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.key !== "") {
      writer.uint32(18).string(message.key);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.active !== false) {
      writer.uint32(32).bool(message.active);
    }
    if (message.rolloutPct !== 0) {
      writer.uint32(40).int32(message.rolloutPct);
    }
    if (message.filters !== undefined) {
      Struct.encode(Struct.wrap(message.filters), writer.uint32(50).fork()).join();
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FeatureFlagResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFeatureFlagResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.active = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.rolloutPct = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.filters = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FeatureFlagResponse {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      active: isSet(object.active) ? globalThis.Boolean(object.active) : false,
      rolloutPct: isSet(object.rolloutPct)
        ? globalThis.Number(object.rolloutPct)
        : isSet(object.rollout_pct)
        ? globalThis.Number(object.rollout_pct)
        : 0,
      filters: isObject(object.filters) ? object.filters : undefined,
      createdAt: isSet(object.createdAt)
        ? fromJsonTimestamp(object.createdAt)
        : isSet(object.created_at)
        ? fromJsonTimestamp(object.created_at)
        : undefined,
    };
  },

  toJSON(message: FeatureFlagResponse): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.active !== false) {
      obj.active = message.active;
    }
    if (message.rolloutPct !== 0) {
      obj.rolloutPct = Math.round(message.rolloutPct);
    }
    if (message.filters !== undefined) {
      obj.filters = message.filters;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FeatureFlagResponse>, I>>(base?: I): FeatureFlagResponse {
    return FeatureFlagResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FeatureFlagResponse>, I>>(object: I): FeatureFlagResponse {
    const message = createBaseFeatureFlagResponse();
    message.id = object.id ?? "";
    message.key = object.key ?? "";
    message.name = object.name ?? "";
    message.active = object.active ?? false;
    message.rolloutPct = object.rolloutPct ?? 0;
    message.filters = object.filters ?? undefined;
    message.createdAt = object.createdAt ?? undefined;
    return message;
  },
};

function createBaseListFeatureFlagsRequest(): ListFeatureFlagsRequest {
  return { projectId: "" };
}

export const ListFeatureFlagsRequest: MessageFns<ListFeatureFlagsRequest> = {
  encode(message: ListFeatureFlagsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.projectId !== "") {
      writer.uint32(10).string(message.projectId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListFeatureFlagsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListFeatureFlagsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.projectId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListFeatureFlagsRequest {
    return {
      projectId: isSet(object.projectId)
        ? globalThis.String(object.projectId)
        : isSet(object.project_id)
        ? globalThis.String(object.project_id)
        : "",
    };
  },

  toJSON(message: ListFeatureFlagsRequest): unknown {
    const obj: any = {};
    if (message.projectId !== "") {
      obj.projectId = message.projectId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListFeatureFlagsRequest>, I>>(base?: I): ListFeatureFlagsRequest {
    return ListFeatureFlagsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListFeatureFlagsRequest>, I>>(object: I): ListFeatureFlagsRequest {
    const message = createBaseListFeatureFlagsRequest();
    message.projectId = object.projectId ?? "";
    return message;
  },
};

function createBaseListFeatureFlagsResponse(): ListFeatureFlagsResponse {
  return { results: [] };
}

export const ListFeatureFlagsResponse: MessageFns<ListFeatureFlagsResponse> = {
  encode(message: ListFeatureFlagsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.results) {
      FeatureFlagResponse.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListFeatureFlagsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListFeatureFlagsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.results.push(FeatureFlagResponse.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListFeatureFlagsResponse {
    return {
      results: globalThis.Array.isArray(object?.results)
        ? object.results.map((e: any) => FeatureFlagResponse.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListFeatureFlagsResponse): unknown {
    const obj: any = {};
    if (message.results?.length) {
      obj.results = message.results.map((e) => FeatureFlagResponse.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListFeatureFlagsResponse>, I>>(base?: I): ListFeatureFlagsResponse {
    return ListFeatureFlagsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListFeatureFlagsResponse>, I>>(object: I): ListFeatureFlagsResponse {
    const message = createBaseListFeatureFlagsResponse();
    message.results = object.results?.map((e) => FeatureFlagResponse.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCreateFeatureFlagRequest(): CreateFeatureFlagRequest {
  return { projectId: "", key: "", name: "", active: false, rolloutPct: 0, filters: undefined };
}

export const CreateFeatureFlagRequest: MessageFns<CreateFeatureFlagRequest> = {
  encode(message: CreateFeatureFlagRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.projectId !== "") {
      writer.uint32(10).string(message.projectId);
    }
    if (message.key !== "") {
      writer.uint32(18).string(message.key);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.active !== false) {
      writer.uint32(32).bool(message.active);
    }
    if (message.rolloutPct !== 0) {
      writer.uint32(40).int32(message.rolloutPct);
    }
    if (message.filters !== undefined) {
      Struct.encode(Struct.wrap(message.filters), writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateFeatureFlagRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateFeatureFlagRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.projectId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.active = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.rolloutPct = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.filters = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateFeatureFlagRequest {
    return {
      projectId: isSet(object.projectId)
        ? globalThis.String(object.projectId)
        : isSet(object.project_id)
        ? globalThis.String(object.project_id)
        : "",
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      active: isSet(object.active) ? globalThis.Boolean(object.active) : false,
      rolloutPct: isSet(object.rolloutPct)
        ? globalThis.Number(object.rolloutPct)
        : isSet(object.rollout_pct)
        ? globalThis.Number(object.rollout_pct)
        : 0,
      filters: isObject(object.filters) ? object.filters : undefined,
    };
  },

  toJSON(message: CreateFeatureFlagRequest): unknown {
    const obj: any = {};
    if (message.projectId !== "") {
      obj.projectId = message.projectId;
    }
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.active !== false) {
      obj.active = message.active;
    }
    if (message.rolloutPct !== 0) {
      obj.rolloutPct = Math.round(message.rolloutPct);
    }
    if (message.filters !== undefined) {
      obj.filters = message.filters;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateFeatureFlagRequest>, I>>(base?: I): CreateFeatureFlagRequest {
    return CreateFeatureFlagRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateFeatureFlagRequest>, I>>(object: I): CreateFeatureFlagRequest {
    const message = createBaseCreateFeatureFlagRequest();
    message.projectId = object.projectId ?? "";
    message.key = object.key ?? "";
    message.name = object.name ?? "";
    message.active = object.active ?? false;
    message.rolloutPct = object.rolloutPct ?? 0;
    message.filters = object.filters ?? undefined;
    return message;
  },
};

function createBaseUpdateFeatureFlagRequest(): UpdateFeatureFlagRequest {
  return { projectId: "", flagId: "", name: undefined, active: undefined, rolloutPct: undefined, filters: undefined };
}

export const UpdateFeatureFlagRequest: MessageFns<UpdateFeatureFlagRequest> = {
  encode(message: UpdateFeatureFlagRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.projectId !== "") {
      writer.uint32(10).string(message.projectId);
    }
    if (message.flagId !== "") {
      writer.uint32(18).string(message.flagId);
    }
    if (message.name !== undefined) {
      writer.uint32(26).string(message.name);
    }
    if (message.active !== undefined) {
      writer.uint32(32).bool(message.active);
    }
    if (message.rolloutPct !== undefined) {
      writer.uint32(40).int32(message.rolloutPct);
    }
    if (message.filters !== undefined) {
      Struct.encode(Struct.wrap(message.filters), writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateFeatureFlagRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateFeatureFlagRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.projectId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.flagId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.active = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.rolloutPct = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.filters = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateFeatureFlagRequest {
    return {
      projectId: isSet(object.projectId)
        ? globalThis.String(object.projectId)
        : isSet(object.project_id)
        ? globalThis.String(object.project_id)
        : "",
      flagId: isSet(object.flagId)
        ? globalThis.String(object.flagId)
        : isSet(object.flag_id)
        ? globalThis.String(object.flag_id)
        : "",
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      active: isSet(object.active) ? globalThis.Boolean(object.active) : undefined,
      rolloutPct: isSet(object.rolloutPct)
        ? globalThis.Number(object.rolloutPct)
        : isSet(object.rollout_pct)
        ? globalThis.Number(object.rollout_pct)
        : undefined,
      filters: isObject(object.filters) ? object.filters : undefined,
    };
  },

  toJSON(message: UpdateFeatureFlagRequest): unknown {
    const obj: any = {};
    if (message.projectId !== "") {
      obj.projectId = message.projectId;
    }
    if (message.flagId !== "") {
      obj.flagId = message.flagId;
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.active !== undefined) {
      obj.active = message.active;
    }
    if (message.rolloutPct !== undefined) {
      obj.rolloutPct = Math.round(message.rolloutPct);
    }
    if (message.filters !== undefined) {
      obj.filters = message.filters;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateFeatureFlagRequest>, I>>(base?: I): UpdateFeatureFlagRequest {
    return UpdateFeatureFlagRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateFeatureFlagRequest>, I>>(object: I): UpdateFeatureFlagRequest {
    const message = createBaseUpdateFeatureFlagRequest();
    message.projectId = object.projectId ?? "";
    message.flagId = object.flagId ?? "";
    message.name = object.name ?? undefined;
    message.active = object.active ?? undefined;
    message.rolloutPct = object.rolloutPct ?? undefined;
    message.filters = object.filters ?? undefined;
    return message;
  },
};

function createBaseDeleteFeatureFlagRequest(): DeleteFeatureFlagRequest {
  return { projectId: "", flagId: "" };
}

export const DeleteFeatureFlagRequest: MessageFns<DeleteFeatureFlagRequest> = {
  encode(message: DeleteFeatureFlagRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.projectId !== "") {
      writer.uint32(10).string(message.projectId);
    }
    if (message.flagId !== "") {
      writer.uint32(18).string(message.flagId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteFeatureFlagRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteFeatureFlagRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.projectId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.flagId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteFeatureFlagRequest {
    return {
      projectId: isSet(object.projectId)
        ? globalThis.String(object.projectId)
        : isSet(object.project_id)
        ? globalThis.String(object.project_id)
        : "",
      flagId: isSet(object.flagId)
        ? globalThis.String(object.flagId)
        : isSet(object.flag_id)
        ? globalThis.String(object.flag_id)
        : "",
    };
  },

  toJSON(message: DeleteFeatureFlagRequest): unknown {
    const obj: any = {};
    if (message.projectId !== "") {
      obj.projectId = message.projectId;
    }
    if (message.flagId !== "") {
      obj.flagId = message.flagId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteFeatureFlagRequest>, I>>(base?: I): DeleteFeatureFlagRequest {
    return DeleteFeatureFlagRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteFeatureFlagRequest>, I>>(object: I): DeleteFeatureFlagRequest {
    const message = createBaseDeleteFeatureFlagRequest();
    message.projectId = object.projectId ?? "";
    message.flagId = object.flagId ?? "";
    return message;
  },
};

function createBaseDeleteFeatureFlagResponse(): DeleteFeatureFlagResponse {
  return {};
}

export const DeleteFeatureFlagResponse: MessageFns<DeleteFeatureFlagResponse> = {
  encode(_: DeleteFeatureFlagResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteFeatureFlagResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteFeatureFlagResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): DeleteFeatureFlagResponse {
    return {};
  },

  toJSON(_: DeleteFeatureFlagResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteFeatureFlagResponse>, I>>(base?: I): DeleteFeatureFlagResponse {
    return DeleteFeatureFlagResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteFeatureFlagResponse>, I>>(_: I): DeleteFeatureFlagResponse {
    const message = createBaseDeleteFeatureFlagResponse();
    return message;
  },
};

function createBaseEvaluateFlagsRequest(): EvaluateFlagsRequest {
  return { projectId: "", distinctId: "", personProperties: undefined, groups: undefined };
}

export const EvaluateFlagsRequest: MessageFns<EvaluateFlagsRequest> = {
  encode(message: EvaluateFlagsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.projectId !== "") {
      writer.uint32(10).string(message.projectId);
    }
    if (message.distinctId !== "") {
      writer.uint32(18).string(message.distinctId);
    }
    if (message.personProperties !== undefined) {
      Struct.encode(Struct.wrap(message.personProperties), writer.uint32(26).fork()).join();
    }
    if (message.groups !== undefined) {
      Struct.encode(Struct.wrap(message.groups), writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EvaluateFlagsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEvaluateFlagsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.projectId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.distinctId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.personProperties = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.groups = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EvaluateFlagsRequest {
    return {
      projectId: isSet(object.projectId)
        ? globalThis.String(object.projectId)
        : isSet(object.project_id)
        ? globalThis.String(object.project_id)
        : "",
      distinctId: isSet(object.distinctId)
        ? globalThis.String(object.distinctId)
        : isSet(object.distinct_id)
        ? globalThis.String(object.distinct_id)
        : "",
      personProperties: isObject(object.personProperties)
        ? object.personProperties
        : isObject(object.person_properties)
        ? object.person_properties
        : undefined,
      groups: isObject(object.groups) ? object.groups : undefined,
    };
  },

  toJSON(message: EvaluateFlagsRequest): unknown {
    const obj: any = {};
    if (message.projectId !== "") {
      obj.projectId = message.projectId;
    }
    if (message.distinctId !== "") {
      obj.distinctId = message.distinctId;
    }
    if (message.personProperties !== undefined) {
      obj.personProperties = message.personProperties;
    }
    if (message.groups !== undefined) {
      obj.groups = message.groups;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EvaluateFlagsRequest>, I>>(base?: I): EvaluateFlagsRequest {
    return EvaluateFlagsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EvaluateFlagsRequest>, I>>(object: I): EvaluateFlagsRequest {
    const message = createBaseEvaluateFlagsRequest();
    message.projectId = object.projectId ?? "";
    message.distinctId = object.distinctId ?? "";
    message.personProperties = object.personProperties ?? undefined;
    message.groups = object.groups ?? undefined;
    return message;
  },
};

function createBaseEvaluateFlagsResponse(): EvaluateFlagsResponse {
  return { featureFlags: {} };
}

export const EvaluateFlagsResponse: MessageFns<EvaluateFlagsResponse> = {
  encode(message: EvaluateFlagsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    globalThis.Object.entries(message.featureFlags).forEach(([key, value]: [string, boolean]) => {
      EvaluateFlagsResponse_FeatureFlagsEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EvaluateFlagsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEvaluateFlagsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const entry1 = EvaluateFlagsResponse_FeatureFlagsEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.featureFlags[entry1.key] = entry1.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EvaluateFlagsResponse {
    return {
      featureFlags: isObject(object.featureFlags)
        ? (globalThis.Object.entries(object.featureFlags) as [string, any][]).reduce(
          (acc: { [key: string]: boolean }, [key, value]: [string, any]) => {
            acc[key] = globalThis.Boolean(value);
            return acc;
          },
          {},
        )
        : isObject(object.feature_flags)
        ? (globalThis.Object.entries(object.feature_flags) as [string, any][]).reduce(
          (acc: { [key: string]: boolean }, [key, value]: [string, any]) => {
            acc[key] = globalThis.Boolean(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: EvaluateFlagsResponse): unknown {
    const obj: any = {};
    if (message.featureFlags) {
      const entries = globalThis.Object.entries(message.featureFlags) as [string, boolean][];
      if (entries.length > 0) {
        obj.featureFlags = {};
        entries.forEach(([k, v]) => {
          obj.featureFlags[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EvaluateFlagsResponse>, I>>(base?: I): EvaluateFlagsResponse {
    return EvaluateFlagsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EvaluateFlagsResponse>, I>>(object: I): EvaluateFlagsResponse {
    const message = createBaseEvaluateFlagsResponse();
    message.featureFlags = (globalThis.Object.entries(object.featureFlags ?? {}) as [string, boolean][]).reduce(
      (acc: { [key: string]: boolean }, [key, value]: [string, boolean]) => {
        if (value !== undefined) {
          acc[key] = globalThis.Boolean(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseEvaluateFlagsResponse_FeatureFlagsEntry(): EvaluateFlagsResponse_FeatureFlagsEntry {
  return { key: "", value: false };
}

export const EvaluateFlagsResponse_FeatureFlagsEntry: MessageFns<EvaluateFlagsResponse_FeatureFlagsEntry> = {
  encode(message: EvaluateFlagsResponse_FeatureFlagsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== false) {
      writer.uint32(16).bool(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EvaluateFlagsResponse_FeatureFlagsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEvaluateFlagsResponse_FeatureFlagsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EvaluateFlagsResponse_FeatureFlagsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.Boolean(object.value) : false,
    };
  },

  toJSON(message: EvaluateFlagsResponse_FeatureFlagsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== false) {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EvaluateFlagsResponse_FeatureFlagsEntry>, I>>(
    base?: I,
  ): EvaluateFlagsResponse_FeatureFlagsEntry {
    return EvaluateFlagsResponse_FeatureFlagsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EvaluateFlagsResponse_FeatureFlagsEntry>, I>>(
    object: I,
  ): EvaluateFlagsResponse_FeatureFlagsEntry {
    const message = createBaseEvaluateFlagsResponse_FeatureFlagsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? false;
    return message;
  },
};

function createBaseDecideRequest(): DecideRequest {
  return { apiKey: undefined, distinctId: "" };
}

export const DecideRequest: MessageFns<DecideRequest> = {
  encode(message: DecideRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.apiKey !== undefined) {
      writer.uint32(10).string(message.apiKey);
    }
    if (message.distinctId !== "") {
      writer.uint32(18).string(message.distinctId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DecideRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDecideRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.apiKey = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.distinctId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DecideRequest {
    return {
      apiKey: isSet(object.apiKey)
        ? globalThis.String(object.apiKey)
        : isSet(object.api_key)
        ? globalThis.String(object.api_key)
        : undefined,
      distinctId: isSet(object.distinctId)
        ? globalThis.String(object.distinctId)
        : isSet(object.distinct_id)
        ? globalThis.String(object.distinct_id)
        : "",
    };
  },

  toJSON(message: DecideRequest): unknown {
    const obj: any = {};
    if (message.apiKey !== undefined) {
      obj.apiKey = message.apiKey;
    }
    if (message.distinctId !== "") {
      obj.distinctId = message.distinctId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DecideRequest>, I>>(base?: I): DecideRequest {
    return DecideRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DecideRequest>, I>>(object: I): DecideRequest {
    const message = createBaseDecideRequest();
    message.apiKey = object.apiKey ?? undefined;
    message.distinctId = object.distinctId ?? "";
    return message;
  },
};

function createBaseDecideResponse(): DecideResponse {
  return { featureFlags: {} };
}

export const DecideResponse: MessageFns<DecideResponse> = {
  encode(message: DecideResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    globalThis.Object.entries(message.featureFlags).forEach(([key, value]: [string, boolean]) => {
      DecideResponse_FeatureFlagsEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DecideResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDecideResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const entry1 = DecideResponse_FeatureFlagsEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.featureFlags[entry1.key] = entry1.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DecideResponse {
    return {
      featureFlags: isObject(object.featureFlags)
        ? (globalThis.Object.entries(object.featureFlags) as [string, any][]).reduce(
          (acc: { [key: string]: boolean }, [key, value]: [string, any]) => {
            acc[key] = globalThis.Boolean(value);
            return acc;
          },
          {},
        )
        : isObject(object.feature_flags)
        ? (globalThis.Object.entries(object.feature_flags) as [string, any][]).reduce(
          (acc: { [key: string]: boolean }, [key, value]: [string, any]) => {
            acc[key] = globalThis.Boolean(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: DecideResponse): unknown {
    const obj: any = {};
    if (message.featureFlags) {
      const entries = globalThis.Object.entries(message.featureFlags) as [string, boolean][];
      if (entries.length > 0) {
        obj.featureFlags = {};
        entries.forEach(([k, v]) => {
          obj.featureFlags[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DecideResponse>, I>>(base?: I): DecideResponse {
    return DecideResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DecideResponse>, I>>(object: I): DecideResponse {
    const message = createBaseDecideResponse();
    message.featureFlags = (globalThis.Object.entries(object.featureFlags ?? {}) as [string, boolean][]).reduce(
      (acc: { [key: string]: boolean }, [key, value]: [string, boolean]) => {
        if (value !== undefined) {
          acc[key] = globalThis.Boolean(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseDecideResponse_FeatureFlagsEntry(): DecideResponse_FeatureFlagsEntry {
  return { key: "", value: false };
}

export const DecideResponse_FeatureFlagsEntry: MessageFns<DecideResponse_FeatureFlagsEntry> = {
  encode(message: DecideResponse_FeatureFlagsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== false) {
      writer.uint32(16).bool(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DecideResponse_FeatureFlagsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDecideResponse_FeatureFlagsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DecideResponse_FeatureFlagsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.Boolean(object.value) : false,
    };
  },

  toJSON(message: DecideResponse_FeatureFlagsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== false) {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DecideResponse_FeatureFlagsEntry>, I>>(
    base?: I,
  ): DecideResponse_FeatureFlagsEntry {
    return DecideResponse_FeatureFlagsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DecideResponse_FeatureFlagsEntry>, I>>(
    object: I,
  ): DecideResponse_FeatureFlagsEntry {
    const message = createBaseDecideResponse_FeatureFlagsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000).toString();
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (globalThis.Number(t.seconds) || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
